package swing;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import swing.macros.Macro;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dridi family
 */
public class Ajout_machine extends javax.swing.JFrame {

    private Ajout_machine() {
        initComponents();
    }

    public JPanel getPanel_client() {
        return panel_client;
    }

    public void setPanel_client(JPanel panel_client) {
        this.panel_client = panel_client;
    }

    /**
     * Creates new form Gestion_clients
     * @param nom_machine
     */
    
      
     
    Ajout_machine(String nom_machine) {
        initComponents();
        
        this.setLocation(500,50);
        
        this.setTitle(nom_machine);
        
        btn_ajouter_machine.setText( btn_ajouter_machine.getText() + " " + nom_machine );
        
        
        this.setResizable(false);
        
      //  btn_ajouter.setBackground( panel1.getBackground() );
      
      txt_nom_machine.setText(nom_machine);
      
      txt_nom_machine.setEditable(false);
        
      
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panel_client = new javax.swing.JPanel();
        txt_date = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panel_utilisateur = new javax.swing.JPanel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        panel1 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txt_nom_machine = new javax.swing.JTextField();
        txt_1 = new javax.swing.JLabel();
        panel_matricule5 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txt_largeur = new javax.swing.JTextField();
        txt_8 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        txt_designation_article = new javax.swing.JTextField();
        txt_2 = new javax.swing.JLabel();
        btn_ajouter_machine = new javax.swing.JButton();
        panel_matricule14 = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        txt_soufflet_b = new javax.swing.JTextField();
        txt_15 = new javax.swing.JLabel();
        panel_matricule15 = new javax.swing.JPanel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        txt_tirage = new javax.swing.JTextField();
        txt_16 = new javax.swing.JLabel();
        panel_matricule16 = new javax.swing.JPanel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        txt_debit = new javax.swing.JTextField();
        txt_17 = new javax.swing.JLabel();
        panel_matricule9 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        txt_largeur_ruban = new javax.swing.JTextField();
        txt_11 = new javax.swing.JLabel();
        panel_matricule12 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        txt_largeur_totale = new javax.swing.JTextField();
        txt_13 = new javax.swing.JLabel();
        panel_matricule13 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        txt_soufflet_a = new javax.swing.JTextField();
        txt_14 = new javax.swing.JLabel();
        panel_matricule10 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        txt_nbr_pistes = new javax.swing.JTextField();
        txt_12 = new javax.swing.JLabel();
        panel_matricule7 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        txt_epaisseur = new javax.swing.JTextField();
        txt_10 = new javax.swing.JLabel();

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("gestion des utilisateurs");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("gestion des utilisateurs");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/cancel_icon.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_client.setBackground(new java.awt.Color(255, 255, 255));

        txt_date.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_date.setForeground(new java.awt.Color(102, 102, 102));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/login.PNG"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/logout.PNG"))); // NOI18N

        panel_utilisateur.setBackground(new java.awt.Color(255, 255, 255));
        panel_utilisateur.setForeground(new java.awt.Color(51, 0, 51));
        panel_utilisateur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_utilisateur.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        panel_utilisateur.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel1.setBackground(new java.awt.Color(51, 0, 51));

        txt_1.setBackground(new java.awt.Color(51, 0, 51));
        txt_1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_1.setForeground(new java.awt.Color(255, 255, 255));
        txt_1.setText("nom machine :");
        txt_1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_1ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_nom_machine, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jLabel43)
                .addGap(28, 28, 28)
                .addComponent(jLabel39)
                .addGap(45, 45, 45)
                .addComponent(jLabel40)
                .addGap(85, 85, 85)
                .addComponent(jLabel41)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addComponent(txt_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nom_machine)
                .addContainerGap())
        );

        panel_utilisateur.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 270, 60));

        panel_matricule5.setBackground(new java.awt.Color(51, 0, 51));

        txt_largeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_largeurActionPerformed(evt);
            }
        });

        txt_8.setBackground(new java.awt.Color(51, 0, 51));
        txt_8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_8.setForeground(new java.awt.Color(255, 255, 255));
        txt_8.setText("largeur :");
        txt_8.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_8ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel_matricule5Layout = new javax.swing.GroupLayout(panel_matricule5);
        panel_matricule5.setLayout(panel_matricule5Layout);
        panel_matricule5Layout.setHorizontalGroup(
            panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule5Layout.createSequentialGroup()
                        .addComponent(txt_largeur, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel49)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel45)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel46)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel47))
                    .addComponent(txt_8, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule5Layout.setVerticalGroup(
            panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_matricule5Layout.createSequentialGroup()
                .addComponent(txt_8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_largeur)
                .addContainerGap())
        );

        panel_utilisateur.add(panel_matricule5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 270, 60));

        panel2.setBackground(new java.awt.Color(51, 0, 51));

        txt_2.setBackground(new java.awt.Color(51, 0, 51));
        txt_2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_2.setForeground(new java.awt.Color(255, 255, 255));
        txt_2.setText("designation article :");
        txt_2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_2ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(txt_designation_article))
                .addGap(35, 35, 35)
                .addComponent(jLabel53)
                .addGap(28, 28, 28)
                .addComponent(jLabel44)
                .addGap(45, 45, 45)
                .addComponent(jLabel50)
                .addGap(85, 85, 85)
                .addComponent(jLabel51)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addComponent(txt_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_designation_article)
                .addContainerGap())
        );

        panel_utilisateur.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 60));

        btn_ajouter_machine.setBackground(new java.awt.Color(51, 0, 51));
        btn_ajouter_machine.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_ajouter_machine.setText(" ajouter une machine");
        btn_ajouter_machine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouter_machineActionPerformed(evt);
            }
        });

        panel_matricule14.setBackground(new java.awt.Color(51, 0, 51));

        txt_15.setBackground(new java.awt.Color(51, 0, 51));
        txt_15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_15.setForeground(new java.awt.Color(255, 255, 255));
        txt_15.setText("souflet b :");
        txt_15.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_15ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel_matricule14Layout = new javax.swing.GroupLayout(panel_matricule14);
        panel_matricule14.setLayout(panel_matricule14Layout);
        panel_matricule14Layout.setHorizontalGroup(
            panel_matricule14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule14Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel93)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_15, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_matricule14Layout.createSequentialGroup()
                        .addComponent(txt_soufflet_b, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel94)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel90)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel91)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel92)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule14Layout.setVerticalGroup(
            panel_matricule14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule14Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_matricule14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel92, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel91, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel90, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel94, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel93, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule14Layout.createSequentialGroup()
                .addComponent(txt_15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_soufflet_b)
                .addContainerGap())
        );

        panel_matricule15.setBackground(new java.awt.Color(51, 0, 51));

        txt_16.setBackground(new java.awt.Color(51, 0, 51));
        txt_16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_16.setForeground(new java.awt.Color(255, 255, 255));
        txt_16.setText("tirage :");
        txt_16.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_16ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel_matricule15Layout = new javax.swing.GroupLayout(panel_matricule15);
        panel_matricule15.setLayout(panel_matricule15Layout);
        panel_matricule15Layout.setHorizontalGroup(
            panel_matricule15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule15Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel98)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_16, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_matricule15Layout.createSequentialGroup()
                        .addComponent(txt_tirage, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel99)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel95)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel96)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel97)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule15Layout.setVerticalGroup(
            panel_matricule15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule15Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_matricule15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel97, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel96, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel95, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel99, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel98, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule15Layout.createSequentialGroup()
                .addComponent(txt_16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_tirage)
                .addContainerGap())
        );

        panel_matricule16.setBackground(new java.awt.Color(51, 0, 51));

        txt_17.setBackground(new java.awt.Color(51, 0, 51));
        txt_17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_17.setForeground(new java.awt.Color(255, 255, 255));
        txt_17.setText("debit :");
        txt_17.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_17ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel_matricule16Layout = new javax.swing.GroupLayout(panel_matricule16);
        panel_matricule16.setLayout(panel_matricule16Layout);
        panel_matricule16Layout.setHorizontalGroup(
            panel_matricule16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule16Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel103)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_17, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_matricule16Layout.createSequentialGroup()
                        .addComponent(txt_debit, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel104)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel100)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel101)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel102)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule16Layout.setVerticalGroup(
            panel_matricule16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule16Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_matricule16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel102, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel104, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel103, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule16Layout.createSequentialGroup()
                .addComponent(txt_17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_debit)
                .addContainerGap())
        );

        panel_matricule9.setBackground(new java.awt.Color(51, 0, 51));

        txt_11.setBackground(new java.awt.Color(51, 0, 51));
        txt_11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_11.setForeground(new java.awt.Color(255, 255, 255));
        txt_11.setText("largeur ruban :");
        txt_11.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_11ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel_matricule9Layout = new javax.swing.GroupLayout(panel_matricule9);
        panel_matricule9.setLayout(panel_matricule9Layout);
        panel_matricule9Layout.setHorizontalGroup(
            panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel64)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_11, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_matricule9Layout.createSequentialGroup()
                        .addComponent(txt_largeur_ruban, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel65)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel61)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel62)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel63)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule9Layout.setVerticalGroup(
            panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule9Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_matricule9Layout.createSequentialGroup()
                .addComponent(txt_11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_largeur_ruban)
                .addContainerGap())
        );

        panel_matricule12.setBackground(new java.awt.Color(51, 0, 51));

        txt_13.setBackground(new java.awt.Color(51, 0, 51));
        txt_13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_13.setForeground(new java.awt.Color(255, 255, 255));
        txt_13.setText("largeur totale :");
        txt_13.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_13ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel_matricule12Layout = new javax.swing.GroupLayout(panel_matricule12);
        panel_matricule12.setLayout(panel_matricule12Layout);
        panel_matricule12Layout.setHorizontalGroup(
            panel_matricule12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule12Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel82)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_13, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_matricule12Layout.createSequentialGroup()
                        .addComponent(txt_largeur_totale, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel83)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel79)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel80)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel81)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule12Layout.setVerticalGroup(
            panel_matricule12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule12Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_matricule12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel81, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel79, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel82, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule12Layout.createSequentialGroup()
                .addComponent(txt_13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_largeur_totale)
                .addContainerGap())
        );

        panel_matricule13.setBackground(new java.awt.Color(51, 0, 51));

        txt_14.setBackground(new java.awt.Color(51, 0, 51));
        txt_14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_14.setForeground(new java.awt.Color(255, 255, 255));
        txt_14.setText("souflet a :");
        txt_14.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_14ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel_matricule13Layout = new javax.swing.GroupLayout(panel_matricule13);
        panel_matricule13.setLayout(panel_matricule13Layout);
        panel_matricule13Layout.setHorizontalGroup(
            panel_matricule13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule13Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel88)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_14, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_matricule13Layout.createSequentialGroup()
                        .addComponent(txt_soufflet_a, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel89)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel85)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel86)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel87)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule13Layout.setVerticalGroup(
            panel_matricule13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule13Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_matricule13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel87, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel86, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel85, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel89, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel88, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule13Layout.createSequentialGroup()
                .addComponent(txt_14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_soufflet_a)
                .addContainerGap())
        );

        panel_matricule10.setBackground(new java.awt.Color(51, 0, 51));

        txt_12.setBackground(new java.awt.Color(51, 0, 51));
        txt_12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_12.setForeground(new java.awt.Color(255, 255, 255));
        txt_12.setText("nbr de pistes :");
        txt_12.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_12ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel_matricule10Layout = new javax.swing.GroupLayout(panel_matricule10);
        panel_matricule10.setLayout(panel_matricule10Layout);
        panel_matricule10Layout.setHorizontalGroup(
            panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel70)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_12, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_matricule10Layout.createSequentialGroup()
                        .addComponent(txt_nbr_pistes, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel71)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel67)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel68)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel69)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule10Layout.setVerticalGroup(
            panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule10Layout.createSequentialGroup()
                .addComponent(txt_12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nbr_pistes, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_matricule7.setBackground(new java.awt.Color(51, 0, 51));

        txt_10.setBackground(new java.awt.Color(51, 0, 51));
        txt_10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_10.setForeground(new java.awt.Color(255, 255, 255));
        txt_10.setText("epaisseur :");
        txt_10.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_10ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel_matricule7Layout = new javax.swing.GroupLayout(panel_matricule7);
        panel_matricule7.setLayout(panel_matricule7Layout);
        panel_matricule7Layout.setHorizontalGroup(
            panel_matricule7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_10, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_matricule7Layout.createSequentialGroup()
                        .addComponent(txt_epaisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel59)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel55)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel56)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel57)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule7Layout.setVerticalGroup(
            panel_matricule7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panel_matricule7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_matricule7Layout.createSequentialGroup()
                .addComponent(txt_10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_epaisseur, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_clientLayout = new javax.swing.GroupLayout(panel_client);
        panel_client.setLayout(panel_clientLayout);
        panel_clientLayout.setHorizontalGroup(
            panel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_clientLayout.createSequentialGroup()
                .addGroup(panel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_clientLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panel_clientLayout.createSequentialGroup()
                                    .addGap(236, 236, 236)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txt_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_clientLayout.createSequentialGroup()
                                .addGroup(panel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panel_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel_clientLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(panel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(panel_matricule7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(panel_matricule10, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panel_matricule9, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panel_matricule12, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panel_matricule13, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panel_matricule14, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panel_matricule15, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panel_matricule16, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panel_clientLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btn_ajouter_machine, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        panel_clientLayout.setVerticalGroup(
            panel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_clientLayout.createSequentialGroup()
                .addGroup(panel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_clientLayout.createSequentialGroup()
                        .addComponent(panel_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_matricule7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(panel_clientLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panel_matricule9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_matricule12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_matricule13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_matricule14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_matricule15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(panel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_matricule10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_matricule16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(btn_ajouter_machine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(639, 639, 639)
                .addGroup(panel_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel17))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_client, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
     
    
    
    
    private void txt_1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_1ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_1ComponentResized

    private void txt_8ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_8ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_8ComponentResized

    private void txt_10ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_10ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_10ComponentResized

    private void txt_11ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_11ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_11ComponentResized

    private void txt_12ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_12ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_12ComponentResized

    private void txt_13ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_13ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_13ComponentResized

    private void txt_14ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_14ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_14ComponentResized

    private void btn_ajouter_machineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouter_machineActionPerformed
        //click bouton ajouter
        
        
        System.out.println("le cb = " + this.getTitle() );
        
        // varex
        
        if( this.getTitle().equals("Varex") ){
            try {
                new Gestion_article().getCb_varex().setEnabled(true);
                //bdd insert
                
                inserer_machine();
        
                
            } catch (SQLException ex) {
                Logger.getLogger(Ajout_machine.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
      
        // macchi1
        
        
        
         if( this.getTitle().equals("MacchiI") ){
            try {
                new Gestion_article().getCb_Macchi1().setEnabled(true);
                // bdd insert
                
                inserer_machine();
                
       
                
            } catch (SQLException ex) {
                Logger.getLogger(Ajout_machine.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        //macchi2
        
        
        
         if( this.getTitle().equals("MacchiII") ){
            try {
                new Gestion_article().getCb_Macchi2().setEnabled(true);
                //inserer une ligne dans table machine
                inserer_machine();
            } catch (SQLException ex) {
                Logger.getLogger(Ajout_machine.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
         // b90i
         
         
         
          if( this.getTitle().equals("B90I") ){
            try {
                new Gestion_article().getCb_B90I().setEnabled(true);
                // inserer une ligne dans table machine
                 inserer_machine();
                
            } catch (SQLException ex) {
                Logger.getLogger(Ajout_machine.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
         
        // b90ii
        
         if( this.getTitle().equals("B90II") ){
            try {
                new Gestion_article().getCb_B90II().setEnabled(true);
                // insersion une ligne dans la table machine
                
                 inserer_machine();
            } catch (SQLException ex) {
                Logger.getLogger(Ajout_machine.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
         
         
        
    }//GEN-LAST:event_btn_ajouter_machineActionPerformed

    private void txt_largeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_largeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_largeurActionPerformed

    private void txt_2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_2ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_2ComponentResized

    private void txt_15ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_15ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_15ComponentResized

    private void txt_16ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_16ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_16ComponentResized

    private void txt_17ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_17ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_17ComponentResized

      
 
    public void exit() {
this.dispose();
}
    
    
    
   static  String machines[] = {"Varex", "B90I", "B90II" , "MacchiI","MacchiII" };
    
    private static Ajout_machine instance_varex = new Ajout_machine(machines[0]);

     private static Ajout_machine instance_b90i = new Ajout_machine(machines[1]);
     
      private static Ajout_machine instance_b90ii = new Ajout_machine(machines[2]);
      
       private static Ajout_machine instance_macchi1 = new Ajout_machine(machines[3]);
       
        private static Ajout_machine instance_macchi2 = new Ajout_machine(machines[4]);
    
    
   //make the constructor private so that this class cannot be
   //instantiated
 

   //Get the only object available
   public static Ajout_machine getInstance_varex(){
      return instance_varex;
   }
    
  
    public static Ajout_machine getInstance_b90i(){
      return instance_b90i;
   }
    
    
     public static Ajout_machine getInstance_b90ii(){
      return instance_b90ii;
   }
    
    
     
       public static Ajout_machine getInstance_machi1(){
      return instance_macchi1;
   }
    
    
       
         public static Ajout_machine getInstance_macchi2() {
      return instance_macchi2;
   }
    
    
    

         
         public void inserer_machine() throws SQLException{
         
             
               // btn enregistrer
        
          // btouon enregistrer ( inserer )
        
          // date format
       
          String designation_article = txt_designation_article.getText();
           //String nom_machine = this.getTitle();
           String nom_machine = txt_nom_machine.getText();
          String largeur = txt_largeur.getText(); 
          String epaisseur = txt_epaisseur.getText();
          String nbr_pistes = txt_nbr_pistes.getText();
          String largeur_ruban = txt_largeur_ruban.getText();
          String largeur_totale = txt_largeur_totale.getText();
          String soufflet_a = txt_soufflet_a.getText();
          String soufflet_b = txt_soufflet_b.getText();
          String tirage = txt_tirage.getText();
          String debit = txt_debit.getText();
          
       
       String url;  
            Connection con = null;  
            try {  
                Class.forName("com.mysql.jdbc.Driver");  
            url="jdbc:mysql://localhost:3306/ahmed";  
                con = DriverManager.getConnection(url,"root","Aminedridi11");  
              //  System.out.println("mrigl");  
              
                }  
                catch (Exception e) {  
                System.out.println(e.toString());  
            }
            
        try {
            // login action
            
            Statement stm = con.createStatement();
            
            //execute query

         
         String sql =" INSERT INTO machines (designation,nom_machine,largeur,epaisseur,nbr_pistes,lar_ruban,lar_totale,souflet_a,souflet_b,tirage,debit) VALUES ('"+designation_article+"','"+nom_machine+"',"+largeur+","+epaisseur+","+nbr_pistes+" , "+largeur_ruban+" , "+largeur_totale+" ,"+soufflet_a + " , "+soufflet_b +" , "+ tirage + " , "+ debit +" ) " ;       
     
         System.out.println(sql);
      
         
        PreparedStatement ps = con.prepareStatement(sql);
         
          ps.executeUpdate();
  
         
         
         JOptionPane.showMessageDialog(this,"une machine de nom = "+ nom_machine +" est ajouté avec succés ");
         
       
         this.dispose();
         
         }
       
         
     
         
         
         catch(Exception ex){
             
         System.out.println(ex.getMessage());
         }
         
         }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajout_machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajout_machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajout_machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajout_machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajout_machine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajouter_machine;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel_client;
    private javax.swing.JPanel panel_matricule10;
    private javax.swing.JPanel panel_matricule12;
    private javax.swing.JPanel panel_matricule13;
    private javax.swing.JPanel panel_matricule14;
    private javax.swing.JPanel panel_matricule15;
    private javax.swing.JPanel panel_matricule16;
    private javax.swing.JPanel panel_matricule5;
    private javax.swing.JPanel panel_matricule7;
    private javax.swing.JPanel panel_matricule9;
    private javax.swing.JPanel panel_utilisateur;
    private javax.swing.JLabel txt_1;
    private javax.swing.JLabel txt_10;
    private javax.swing.JLabel txt_11;
    private javax.swing.JLabel txt_12;
    private javax.swing.JLabel txt_13;
    private javax.swing.JLabel txt_14;
    private javax.swing.JLabel txt_15;
    private javax.swing.JLabel txt_16;
    private javax.swing.JLabel txt_17;
    private javax.swing.JLabel txt_2;
    private javax.swing.JLabel txt_8;
    private javax.swing.JLabel txt_date;
    private javax.swing.JTextField txt_debit;
    private javax.swing.JTextField txt_designation_article;
    private javax.swing.JTextField txt_epaisseur;
    private javax.swing.JTextField txt_largeur;
    private javax.swing.JTextField txt_largeur_ruban;
    private javax.swing.JTextField txt_largeur_totale;
    private javax.swing.JTextField txt_nbr_pistes;
    private javax.swing.JTextField txt_nom_machine;
    private javax.swing.JTextField txt_soufflet_a;
    private javax.swing.JTextField txt_soufflet_b;
    private javax.swing.JTextField txt_tirage;
    // End of variables declaration//GEN-END:variables
}
