/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dridi family
 */
public class Gestion_matiere_premiere extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_matiere_premiere
     */
    public Gestion_matiere_premiere() throws SQLException {
        initComponents();
        remplir_users_tab();
        fill_combo_four();
        txt_des1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_mp = new javax.swing.JPanel();
        txt_date = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_mp = new javax.swing.JTable();
        txt_recherche = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panel_utilisateur = new javax.swing.JPanel();
        panel_matricule4 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txt_quantite = new javax.swing.JTextField();
        panel_matricule8 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        txt_designation = new javax.swing.JTextField();
        btn_ajouter = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        panel_matricule5 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txt_prix_unitaire = new javax.swing.JTextField();
        panel_matricule10 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        delais_livraison = new com.toedter.calendar.JDateChooser();
        panel_matricule11 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        txt_reference = new javax.swing.JTextField();
        panel_matricule12 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        txt_prix_globale = new javax.swing.JTextField();
        panel_matricule13 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        combo_type = new javax.swing.JComboBox<>();
        panel_matricule14 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        combo_fournisseur = new javax.swing.JComboBox<>();
        panel_matricule9 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        txt_des1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_mp.setBackground(new java.awt.Color(255, 255, 255));

        txt_date.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_date.setForeground(new java.awt.Color(102, 102, 102));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/login.PNG"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/logout.PNG"))); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        table_mp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        table_mp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "designation", "quantite", "prix unitaire", "ecart type", "prix globale", "type", "fournisseur", "delais livraison"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_mp.setGridColor(new java.awt.Color(255, 255, 255));
        table_mp.setRowHeight(22);
        table_mp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_mpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_mp);

        txt_recherche.setBackground(new java.awt.Color(123, 156, 225));
        txt_recherche.setForeground(new java.awt.Color(255, 255, 255));
        txt_recherche.setBorder(null);
        txt_recherche.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_recherche.setPreferredSize(new java.awt.Dimension(2, 20));
        txt_recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rechercheActionPerformed(evt);
            }
        });
        txt_recherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rechercheKeyTyped(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/search-icon.png"))); // NOI18N
        jLabel1.setText("search");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("gestion des utilisateurs");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("gestion des utilisateurs");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 255));
        jLabel7.setText("gestion des matieres premieres");

        panel_utilisateur.setBackground(new java.awt.Color(120, 168, 252));
        panel_utilisateur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_matricule4.setBackground(new java.awt.Color(84, 127, 206));

        jLabel44.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel44.setText("quantite :");

        javax.swing.GroupLayout panel_matricule4Layout = new javax.swing.GroupLayout(panel_matricule4);
        panel_matricule4.setLayout(panel_matricule4Layout);
        panel_matricule4Layout.setHorizontalGroup(
            panel_matricule4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule4Layout.createSequentialGroup()
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(jLabel43)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel39)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel40)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel41))
                    .addComponent(txt_quantite, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panel_matricule4Layout.setVerticalGroup(
            panel_matricule4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule4Layout.createSequentialGroup()
                .addGroup(panel_matricule4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panel_matricule4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_matricule4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel44)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule4Layout.createSequentialGroup()
                        .addComponent(txt_quantite, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel_utilisateur.add(panel_matricule4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 270, 60));

        panel_matricule8.setBackground(new java.awt.Color(84, 127, 206));

        jLabel54.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel54.setText("designation :");

        javax.swing.GroupLayout panel_matricule8Layout = new javax.swing.GroupLayout(panel_matricule8);
        panel_matricule8.setLayout(panel_matricule8Layout);
        panel_matricule8Layout.setHorizontalGroup(
            panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule8Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule8Layout.createSequentialGroup()
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_matricule8Layout.createSequentialGroup()
                        .addComponent(txt_designation, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215)
                        .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_matricule8Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel53)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel33)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel34)
                                .addGap(85, 85, 85)
                                .addComponent(jLabel51))
                            .addGroup(panel_matricule8Layout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(270, 270, 270))))
        );
        panel_matricule8Layout.setVerticalGroup(
            panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel_matricule8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_matricule8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_designation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_utilisateur.add(panel_matricule8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 270, 60));

        btn_ajouter.setBackground(new java.awt.Color(255, 255, 255));
        btn_ajouter.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_ajouter.setForeground(new java.awt.Color(51, 102, 255));
        btn_ajouter.setText("ajouter");
        btn_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouterActionPerformed(evt);
            }
        });
        panel_utilisateur.add(btn_ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 80, 20));

        btn_modifier.setBackground(new java.awt.Color(255, 255, 255));
        btn_modifier.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_modifier.setForeground(new java.awt.Color(51, 102, 255));
        btn_modifier.setText("modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });
        panel_utilisateur.add(btn_modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 90, 20));

        btn_supprimer.setBackground(new java.awt.Color(255, 255, 255));
        btn_supprimer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_supprimer.setForeground(new java.awt.Color(51, 102, 255));
        btn_supprimer.setText("supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });
        panel_utilisateur.add(btn_supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 100, 20));

        panel_matricule5.setBackground(new java.awt.Color(84, 127, 206));

        jLabel50.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel50.setText("prix unitaire :");

        javax.swing.GroupLayout panel_matricule5Layout = new javax.swing.GroupLayout(panel_matricule5);
        panel_matricule5.setLayout(panel_matricule5Layout);
        panel_matricule5Layout.setHorizontalGroup(
            panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule5Layout.createSequentialGroup()
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel49)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel45)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel46)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel47))
                    .addComponent(txt_prix_unitaire, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule5Layout.setVerticalGroup(
            panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule5Layout.createSequentialGroup()
                .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_matricule5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel50)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule5Layout.createSequentialGroup()
                        .addComponent(txt_prix_unitaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel_utilisateur.add(panel_matricule5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 270, 60));

        panel_matricule10.setBackground(new java.awt.Color(84, 127, 206));

        jLabel72.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel72.setText("delais livraison :");

        javax.swing.GroupLayout panel_matricule10Layout = new javax.swing.GroupLayout(panel_matricule10);
        panel_matricule10.setLayout(panel_matricule10Layout);
        panel_matricule10Layout.setHorizontalGroup(
            panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel70)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule10Layout.createSequentialGroup()
                        .addComponent(delais_livraison, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel71)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel67)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel68)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel69))
                    .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule10Layout.setVerticalGroup(
            panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule10Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule10Layout.createSequentialGroup()
                        .addGroup(panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel70, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                    .addGroup(panel_matricule10Layout.createSequentialGroup()
                        .addComponent(delais_livraison, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))))
        );

        panel_utilisateur.add(panel_matricule10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 270, 70));

        panel_matricule11.setBackground(new java.awt.Color(84, 127, 206));

        jLabel62.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel62.setText("reference :");

        javax.swing.GroupLayout panel_matricule11Layout = new javax.swing.GroupLayout(panel_matricule11);
        panel_matricule11.setLayout(panel_matricule11Layout);
        panel_matricule11Layout.setHorizontalGroup(
            panel_matricule11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule11Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panel_matricule11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule11Layout.createSequentialGroup()
                        .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_matricule11Layout.createSequentialGroup()
                        .addComponent(txt_reference, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215)
                        .addGroup(panel_matricule11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_matricule11Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel61)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel37)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel38)
                                .addGap(85, 85, 85)
                                .addComponent(jLabel59))
                            .addGroup(panel_matricule11Layout.createSequentialGroup()
                                .addComponent(jLabel60)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(270, 270, 270))))
        );
        panel_matricule11Layout.setVerticalGroup(
            panel_matricule11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel_matricule11Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panel_matricule11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_matricule11Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel62)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_reference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_utilisateur.add(panel_matricule11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 270, 60));

        panel_matricule12.setBackground(new java.awt.Color(84, 127, 206));

        jLabel78.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel78.setText("prix globale :");

        javax.swing.GroupLayout panel_matricule12Layout = new javax.swing.GroupLayout(panel_matricule12);
        panel_matricule12.setLayout(panel_matricule12Layout);
        panel_matricule12Layout.setHorizontalGroup(
            panel_matricule12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule12Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel76)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule12Layout.createSequentialGroup()
                        .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel77)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel73)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel74)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel75))
                    .addComponent(txt_prix_globale, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule12Layout.setVerticalGroup(
            panel_matricule12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule12Layout.createSequentialGroup()
                .addGroup(panel_matricule12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule12Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panel_matricule12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel75, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel77, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_matricule12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel78)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel76, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_matricule12Layout.createSequentialGroup()
                        .addComponent(txt_prix_globale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))))
        );

        panel_utilisateur.add(panel_matricule12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 270, 60));

        panel_matricule13.setBackground(new java.awt.Color(84, 127, 206));

        jLabel84.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel84.setText("type :");

        combo_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "03", "07", "exceed" }));

        javax.swing.GroupLayout panel_matricule13Layout = new javax.swing.GroupLayout(panel_matricule13);
        panel_matricule13.setLayout(panel_matricule13Layout);
        panel_matricule13Layout.setHorizontalGroup(
            panel_matricule13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule13Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel82)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule13Layout.createSequentialGroup()
                        .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel83)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel79)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel80)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel81))
                    .addComponent(combo_type, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule13Layout.setVerticalGroup(
            panel_matricule13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule13Layout.createSequentialGroup()
                .addGroup(panel_matricule13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule13Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panel_matricule13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel81, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel79, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_matricule13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel84)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel82, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addGroup(panel_matricule13Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(combo_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        panel_utilisateur.add(panel_matricule13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 270, 60));

        panel_matricule14.setBackground(new java.awt.Color(84, 127, 206));

        jLabel90.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel90.setText("fournisseur :");

        javax.swing.GroupLayout panel_matricule14Layout = new javax.swing.GroupLayout(panel_matricule14);
        panel_matricule14.setLayout(panel_matricule14Layout);
        panel_matricule14Layout.setHorizontalGroup(
            panel_matricule14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule14Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel88)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule14Layout.createSequentialGroup()
                        .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel89)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel85)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel86)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel87))
                    .addComponent(combo_fournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule14Layout.setVerticalGroup(
            panel_matricule14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule14Layout.createSequentialGroup()
                .addGroup(panel_matricule14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule14Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panel_matricule14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel87, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel86, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel85, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel89, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_matricule14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel90)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel88, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addGroup(panel_matricule14Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(combo_fournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        panel_utilisateur.add(panel_matricule14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 270, 60));

        javax.swing.GroupLayout panel_mpLayout = new javax.swing.GroupLayout(panel_mp);
        panel_mp.setLayout(panel_mpLayout);
        panel_mpLayout.setHorizontalGroup(
            panel_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_mpLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_mpLayout.createSequentialGroup()
                .addComponent(panel_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_mpLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mpLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(panel_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_mpLayout.createSequentialGroup()
                    .addGap(292, 292, 292)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(446, Short.MAX_VALUE)))
            .addGroup(panel_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_mpLayout.createSequentialGroup()
                    .addGap(245, 245, 245)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(399, Short.MAX_VALUE)))
        );
        panel_mpLayout.setVerticalGroup(
            panel_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mpLayout.createSequentialGroup()
                .addGroup(panel_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_mpLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel7)
                        .addGap(204, 204, 204)
                        .addGroup(panel_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(213, 213, 213)
                .addComponent(txt_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(499, 499, 499)
                .addGroup(panel_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel17))
                .addContainerGap())
            .addGroup(panel_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_mpLayout.createSequentialGroup()
                    .addGap(648, 648, 648)
                    .addComponent(jLabel2)
                    .addContainerGap(618, Short.MAX_VALUE)))
            .addGroup(panel_mpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_mpLayout.createSequentialGroup()
                    .addGap(648, 648, 648)
                    .addComponent(jLabel5)
                    .addContainerGap(618, Short.MAX_VALUE)))
        );

        panel_matricule9.setBackground(new java.awt.Color(84, 127, 206));

        jLabel58.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel58.setText("designation :");

        javax.swing.GroupLayout panel_matricule9Layout = new javax.swing.GroupLayout(panel_matricule9);
        panel_matricule9.setLayout(panel_matricule9Layout);
        panel_matricule9Layout.setHorizontalGroup(
            panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule9Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule9Layout.createSequentialGroup()
                        .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_matricule9Layout.createSequentialGroup()
                        .addGroup(panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_des1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(215, 215, 215)
                        .addGroup(panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_matricule9Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel57)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel35)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel36)
                                .addGap(85, 85, 85)
                                .addComponent(jLabel55))
                            .addGroup(panel_matricule9Layout.createSequentialGroup()
                                .addComponent(jLabel56)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(270, 270, 270))))
        );
        panel_matricule9Layout.setVerticalGroup(
            panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule9Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_des1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_mp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_matricule9, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_mp, javax.swing.GroupLayout.PREFERRED_SIZE, 537, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 233, Short.MAX_VALUE)
                    .addComponent(panel_matricule9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 234, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rechercheActionPerformed

    public JPanel getPanel_mp() {
        return panel_mp;
    }

    public void setPanel_mp(JPanel panel_mp) {
        this.panel_mp = panel_mp;
    }

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        // btn supp
        
        
        
        //supp
        
        
            String url;  
            Connection con = null;  
            try {  
                Class.forName("com.mysql.jdbc.Driver");  
            url="jdbc:mysql://localhost:3306/ahmed";  
                con = DriverManager.getConnection(url,"root","Aminedridi11");  
              //  System.out.println("mrigl");  
              
                }  
                catch (Exception e) {  
                System.out.println(e.toString());  
            }
            
        try {
            // login action
            
            Statement stm = con.createStatement();
            
            //execute query
            
            // input pour l'update celon la matricule
         
      
            //UPDATE client SET rue = '49 Rue Ameline',ville = 'Saint-Eustache-la-Forêt',code_postal = '76210' WHERE id = 2
        
              
         String sql =" DELETE FROM matiere_premiere WHERE designation ='"+txt_designation.getText()+"'" ; 
         
         System.out.println(sql);
         
        
         
        PreparedStatement ps = con.prepareStatement(sql);
         
          ps.executeUpdate();
  
         
      //   System.out.println("le utilisateur de nom "+nom+" est supprimé !!!  ");
         
         JOptionPane.showMessageDialog(this,"la matiere premiere est supprimé avec succés  ");
       
       
     
   
        } catch (SQLException ex) {
            
            System.out.println(ex.getMessage());
            
        }
        
        // supprimer la ligne selectionnée dans jtbale
        
         int SelectedRowIndex = table_mp.getSelectedRow();
            
            
                
                 DefaultTableModel model2 = (DefaultTableModel) table_mp.getModel();
                 // effacer la ligne selectionnée
                 
                 
                 model2.removeRow(SelectedRowIndex);
                 
                 
             //    txt_ref.setText("");  txt_des.setText(""); txt_quantite.setText(""); 
                 
              //   txt_prix_unitaire.setText("");
    
        
        
    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void btn_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouterActionPerformed
        // btn ajouter
        
          // btn enregistrer
        
          // btouon enregistrer ( inserer )
        
     // btouon enregistrer ( inserer )
        
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        
           
           String date_livraison = df.format( delais_livraison.getDate() );
           
           
           String type = combo_type.getSelectedItem().toString();
           
           
           String reference = txt_reference.getText();
           
           String designation = txt_designation.getText();
           
           
           String quantite = txt_quantite.getText();
           
           String prix_unitaire = txt_prix_unitaire.getText();
           
           
           String prix_globale = txt_prix_globale.getText();
           
           String fournisseur = combo_fournisseur.getSelectedItem().toString();
        
       String url;  
            Connection con = null;  
            try {  
                Class.forName("com.mysql.jdbc.Driver");  
            url="jdbc:mysql://localhost:3306/ahmed";  
                con = DriverManager.getConnection(url,"root","Aminedridi11");  
              //  System.out.println("mrigl");  
              
                }  
                catch (Exception e) {  
                System.out.println(e.toString());  
            }
            
        try {
            // login action
            
            Statement stm = con.createStatement();
            
            //execute query

         
         String sql =" INSERT INTO matiere_premiere (reference,designation,quantite,prix_unitaire,prix_globale,type,fournisseur,delaislivraison) VALUES ('"+reference+"','"+designation+"','"+quantite+"','"+prix_unitaire+"','"+prix_globale+"','"+type+"','"+fournisseur+"','"+date_livraison+"') " ;       
     
         System.out.println(sql);
      
         
        PreparedStatement ps = con.prepareStatement(sql);
         
          ps.executeUpdate();
  
         
         
         JOptionPane.showMessageDialog(this,"la matiere premiere est ajouté avec succés ");
         
       
       
     
   
       // remplir le tab avec nouveau utilisateur
       
    
                
                 DefaultTableModel model3 = (DefaultTableModel) table_mp.getModel();
       
                 
                 
       Object[] table = new Object[8];
   
               
      table[0] = reference ;
       
       table[1] = designation ;

       
       table[2] = quantite ;   
       
        table[3] = prix_unitaire ;   
        
        table[4] = prix_globale ;   
        
        table[5] = type ;   
     
       table[6] = fournisseur ;  
       
       table[7] = date_livraison ;  
                 
       
       
       
       
       model3.addRow(table);
       
      
      
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
        
        
        
    
        
    
        
        
        
        
        
    }//GEN-LAST:event_btn_ajouterActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
        // btn modifier
        
           // bouton modifieir
        
        
        // modifier utiliateur 
        
        // nom et prenom ne change pas dans la modification
        
        // modifier user
        
            String url;  
            Connection con = null;  
            try {  
                Class.forName("com.mysql.jdbc.Driver");  
            url="jdbc:mysql://localhost:3306/ahmed";  
                con = DriverManager.getConnection(url,"root","Aminedridi11");  
              //  System.out.println("mrigl");  
              
                }  
                catch (Exception e) {  
                System.out.println(e.toString());  
            }
            
        try {
            // login action
            
            Statement stm = con.createStatement();
            
            //execute query
            
            // input pour l'update celon la matricule
            
        
      
            
            //UPDATE client SET rue = '49 Rue Ameline',ville = 'Saint-Eustache-la-Forêt',code_postal = '76210' WHERE id = 2
         DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        
           
           String date_livraison = df.format( delais_livraison.getDate() );
           
           
           String type = combo_type.getSelectedItem().toString();
           
           
           String reference = txt_reference.getText();
           
           String designation = txt_designation.getText();
           
           
           String quantite = txt_quantite.getText();
           
           String prix_unitaire = txt_prix_unitaire.getText();
           
           
           String prix_globale = txt_prix_globale.getText();
           
           String fournisseur = combo_fournisseur.getSelectedItem().toString();
        
              
         String sql =" UPDATE matiere_premiere SET designation = '"+designation+"',quantite ='"+quantite+"',prix_unitaire = '"+prix_unitaire+"',prix_globale ='"+prix_globale+"',type ='"+type+"',fournisseur ='"+fournisseur+"',delaislivraison='"+date_livraison+"'"+" WHERE reference ='"+reference+"' ;" ; 
         
         System.out.println(sql);
 
         
        PreparedStatement ps = con.prepareStatement(sql);
         
          ps.executeUpdate();
  
         
         
         
         JOptionPane.showMessageDialog(this,"la matiere est modifié avec succés ");
       
       
     
   
       // ouvrir la page de consulation des utilisateurs 
      
      
        // modifier le jtable
        
            int SelectedRowIndex = table_mp.getSelectedRow();
            
            
                
                 DefaultTableModel model2 = (DefaultTableModel) table_mp.getModel();
                 // effacer la ligne selectionnée
                 
                 
                 model2.removeRow(SelectedRowIndex);
                 
                 // ajouté la nouvelle ligne
                  
       Object[] table = new Object[8];
   
               
      table[0] = reference ;
       
       table[1] = designation ;

       
       table[2] = quantite ;   
       
        table[3] = prix_unitaire ;   
        
        table[4] = prix_globale ;   
        
        table[5] = type ;   
     
       table[6] = fournisseur ;  
       
       table[7] = date_livraison ;  
                 
       
       
       
       
       
       
       model2.addRow(table);
     
                 
            
        }
        catch(Exception ex){
        
        System.out.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_btn_modifierActionPerformed

    private void table_mpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_mpMouseClicked
        
        // tabel client mouse clicked
        
        
         // table mouse clicked
        
        
        DefaultTableModel model3 = (DefaultTableModel) table_mp.getModel();
        
        int SelectedRowIndex = table_mp.getSelectedRow();
        
        
        
        txt_reference.setText(model3.getValueAt(SelectedRowIndex, 0).toString());
        
        txt_designation.setText(model3.getValueAt(SelectedRowIndex, 1).toString());
        
        
        
        txt_quantite.setText(model3.getValueAt(SelectedRowIndex, 2).toString());
        
        txt_prix_unitaire.setText(model3.getValueAt(SelectedRowIndex, 3).toString());
        
         txt_prix_globale.setText(model3.getValueAt(SelectedRowIndex, 4).toString());
         
         combo_type.setSelectedItem(model3.getValueAt(SelectedRowIndex, 5).toString());
         
         combo_fournisseur.setSelectedItem(model3.getValueAt(SelectedRowIndex, 6).toString());
         
        //  combo_fournisseur.setSelectedItem(model3.getValueAt(SelectedRowIndex, 6).toString());
        
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        
        try {
            Date d1 = df.parse(model3.getValueAt(SelectedRowIndex, 7).toString());
            
            //  txt_tel.setText(model3.getValueAt(SelectedRowIndex, 2).toString());
            
            delais_livraison.setDate(d1);
        }
        
        catch(Exception ex){
        System.out.println(ex.getMessage());
        }
        
       
      //   txt_type.setText(model3.getValueAt(SelectedRowIndex, 3).toString());

      
        
        
    }//GEN-LAST:event_table_mpMouseClicked

    private void txt_rechercheKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rechercheKeyTyped
        // key typed
        
        
           
            
            txt_recherche.getDocument().addDocumentListener(new DocumentListener(){
            
                @Override
                public void insertUpdate(DocumentEvent de) {
                   System.out.println(" insert  " + txt_recherche.getText());
                   recherche(txt_recherche.getText());
                }

                @Override
                public void removeUpdate(DocumentEvent de) {
                    System.out.println(" update  " + txt_recherche.getText());
                    recherche(txt_recherche.getText());
                }

                @Override
                public void changedUpdate(DocumentEvent de) {
                  System.out.println(" delete  " + txt_recherche.getText());
                  recherche(txt_recherche.getText());
                }
            
                });
            
        
    }//GEN-LAST:event_txt_rechercheKeyTyped

    
     

    public void recherche(String text){
    
        
        String url;
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/ahmed";
            con = DriverManager.getConnection(url,"root","Aminedridi11");
            //  System.out.println("mrigl");

        }
        catch (Exception e) {
            System.out.println(e.toString());
        }

        try {
            // login action

            Statement stm = con.createStatement();

      
            
            
               // effacer le tab
                
                
                DefaultTableModel dm = (DefaultTableModel) table_mp.getModel();
            int rowCount = dm.getRowCount();
            //Remove rows one by one from the end of the table
            for (int i = rowCount - 1; i >= 0; i--) {
         dm.removeRow(i);
            }
                
            
            
            
            
         
            // check user
            
            ResultSet rs ; 
            
            String sql1 = " SELECT * FROM `matiere_premiere` WHERE designation like '%"+text+"%' or quantite like '%"+ text +"%' or prix_unitaire LIKE '%"+text+"%' or prix_globale LIKE '%"+text+"%' or type LIKE '%"+text+"%' or fournisseur LIKE '%"+text+"%' or delaislivraison LIKE '%"+text+"%' or reference LIKE '%"+text+"%'  ;"   ;

            System.out.println(sql1);
            
            rs =  stm.executeQuery(sql1);
            
            

            while(rs.next()){
                
             
            
                // remplir le tableau  avec la req select
                String reference = rs.getString("reference");
                
                 String designation = rs.getString("designation");
                 
                String quantite = rs.getString("quantite");
          
              String prix_unitaire = rs.getString("prix_unitaire");

              
              String prix_globale = rs.getString("prix_globale");
              
              
               String type = rs.getString("type");
               
               
                String fournisseur = rs.getString("fournisseur");
                
                
                 String delais_livraison = rs.getString("delaislivraison");
      
              
             
              
                
              //  System.out.println(" info === " +  reference  + designation +   prix_unitaire + prix_globale  +   type  );
  

                // remplir le tableau 
                
               
                  
       Object[] table = new Object[8];
   
               
      table[0] = reference ;
       
       table[1] = designation ;

       
       table[2] = quantite ;   
       
        table[3] = prix_unitaire ;   
        
        table[4] = prix_globale ;   
        
        table[5] = type ;   
     
       table[6] = fournisseur ;  
       
       table[7] = delais_livraison ;  
                 
       
       
  
       
       dm.addRow(table);
       

            
           
            }
               
    }                                        

        catch(Exception ex){
            System.out.println(ex.getMessage());
        } 
        
        
    
    }
    
    
    
    
    
    
     
        private void remplir_users_tab(){
        
        
        ResultSet rs;
        String url;
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/ahmed";
            con = DriverManager.getConnection(url,"root","Aminedridi11");
            //  System.out.println("mrigl");

        }
        catch (Exception e) {
            System.out.println(e.toString());
        }

        try {
            // login action

            Statement stm = con.createStatement();

      

            rs =  stm.executeQuery("SELECT * FROM `matiere_premiere`");

            //rs = stm.executeQuery("SELECT * FROM admin");

            while(rs.next()){

              
                 
                // remplir le tableau  avec la req select
                String reference = rs.getString("reference");
                
                 String designation = rs.getString("designation");
                 
                String quantite = rs.getString("quantite");
          
              String prix_unitaire = rs.getString("prix_unitaire");

              
              String prix_globale = rs.getString("prix_globale");
              
              
               String type = rs.getString("type");
               
               
                String fournisseur = rs.getString("fournisseur");
                
                
                 String delais_livraison = rs.getString("delaislivraison");
      
              
                
             //   System.out.println(nom  + prenom +  + departement + mot_de_passe);
  

                // remplir le tableau 
                
                
                
                 DefaultTableModel model2 = (DefaultTableModel) table_mp.getModel();
       
       Object[] table = new Object[8];
   
               
      table[0] = reference;
       
       table[1] = designation;

       
       table[2] = quantite; 
       
       
       
       table[3] = prix_unitaire;
   
       table[4] = prix_globale;
       
       table[5] = type;
       
       
       table[6] = fournisseur;
       
         table[7] = delais_livraison;
       
       model2.addRow(table);
       

            }
        
        }
        
          catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
 
    }  
    
    
    
        
        
        
        public void fill_combo_four() throws SQLException{
        
        
            
        String url;
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/ahmed";
            con = DriverManager.getConnection(url,"root","Aminedridi11");
            //  System.out.println("mrigl");

        }
        catch (Exception e) {
            System.out.println(e.toString());
        }

            // login action

            Statement stm = con.createStatement();

           
           
            
         
            // check user
            
            ResultSet rs ; 
            
            String sql1 = "SELECT * FROM `fournisseur`  ";

            System.out.println(sql1);
            
            rs =  stm.executeQuery(sql1);
            
            

            //rs = stm.executeQuery("SELECT * FROM admin");

            while(rs.next()){
 
  
             combo_fournisseur.addItem(rs.getString("reference"));
           
            }
               
            
            
            
        }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_matiere_premiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_matiere_premiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_matiere_premiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_matiere_premiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Gestion_matiere_premiere().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Gestion_matiere_premiere.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajouter;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_supprimer;
    private javax.swing.JComboBox<String> combo_fournisseur;
    private javax.swing.JComboBox<String> combo_type;
    private com.toedter.calendar.JDateChooser delais_livraison;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JPanel panel_matricule10;
    private javax.swing.JPanel panel_matricule11;
    private javax.swing.JPanel panel_matricule12;
    private javax.swing.JPanel panel_matricule13;
    private javax.swing.JPanel panel_matricule14;
    private javax.swing.JPanel panel_matricule4;
    private javax.swing.JPanel panel_matricule5;
    private javax.swing.JPanel panel_matricule8;
    private javax.swing.JPanel panel_matricule9;
    private javax.swing.JPanel panel_mp;
    private javax.swing.JPanel panel_utilisateur;
    private javax.swing.JTable table_mp;
    private javax.swing.JLabel txt_date;
    private javax.swing.JTextField txt_des1;
    private javax.swing.JTextField txt_designation;
    private javax.swing.JTextField txt_prix_globale;
    private javax.swing.JTextField txt_prix_unitaire;
    private javax.swing.JTextField txt_quantite;
    private javax.swing.JTextField txt_recherche;
    private javax.swing.JTextField txt_reference;
    // End of variables declaration//GEN-END:variables
}
