/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dridi family
 */
public final  class Gestion_vente extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_vente
     * @throws java.sql.SQLException
     */
    public Gestion_vente() throws SQLException {
        initComponents();
        remplir_users_tab();

    }

    public JPanel getPanel_vente() {
        return panel_vente;
    }

    public void setPanel_vente(JPanel panel_vente) {
        this.panel_vente = panel_vente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_vente = new javax.swing.JPanel();
        txt_date2 = new javax.swing.JLabel();
        txt_recherche = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panel_utilisateur = new javax.swing.JPanel();
        panel_matricule4 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txt_quantite = new javax.swing.JTextField();
        panel_matricule8 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        txt_des = new javax.swing.JTextField();
        btn_ajouter = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        panel_matricule5 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txt_ecart_type = new javax.swing.JTextField();
        panel_matricule10 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        txt_moyenne = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_vente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_vente.setBackground(new java.awt.Color(255, 255, 255));

        txt_date2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_date2.setForeground(new java.awt.Color(102, 102, 102));

        txt_recherche.setBackground(new java.awt.Color(123, 156, 225));
        txt_recherche.setForeground(new java.awt.Color(255, 255, 255));
        txt_recherche.setBorder(null);
        txt_recherche.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_recherche.setPreferredSize(new java.awt.Dimension(2, 20));
        txt_recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rechercheActionPerformed(evt);
            }
        });
        txt_recherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rechercheKeyTyped(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/search-icon.png"))); // NOI18N
        jLabel1.setText("search");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 255));
        jLabel9.setText("gestion des ventes");

        panel_utilisateur.setBackground(new java.awt.Color(120, 168, 252));
        panel_utilisateur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_matricule4.setBackground(new java.awt.Color(84, 127, 206));

        jLabel44.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel44.setText("quantite :");

        javax.swing.GroupLayout panel_matricule4Layout = new javax.swing.GroupLayout(panel_matricule4);
        panel_matricule4.setLayout(panel_matricule4Layout);
        panel_matricule4Layout.setHorizontalGroup(
            panel_matricule4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule4Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addGap(154, 154, 154)
                        .addComponent(jLabel43)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel39)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel40)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel41))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_quantite, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panel_matricule4Layout.setVerticalGroup(
            panel_matricule4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule4Layout.createSequentialGroup()
                .addGroup(panel_matricule4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panel_matricule4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_matricule4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel44)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule4Layout.createSequentialGroup()
                        .addComponent(txt_quantite, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel_utilisateur.add(panel_matricule4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 270, 80));

        panel_matricule8.setBackground(new java.awt.Color(84, 127, 206));

        jLabel54.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel54.setText("designation :");

        javax.swing.GroupLayout panel_matricule8Layout = new javax.swing.GroupLayout(panel_matricule8);
        panel_matricule8.setLayout(panel_matricule8Layout);
        panel_matricule8Layout.setHorizontalGroup(
            panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule8Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule8Layout.createSequentialGroup()
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_matricule8Layout.createSequentialGroup()
                        .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_des, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(215, 215, 215)
                        .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_matricule8Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel53)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel33)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel34)
                                .addGap(85, 85, 85)
                                .addComponent(jLabel51))
                            .addGroup(panel_matricule8Layout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(270, 270, 270))))
        );
        panel_matricule8Layout.setVerticalGroup(
            panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_des, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel_utilisateur.add(panel_matricule8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 270, 70));

        btn_ajouter.setBackground(new java.awt.Color(255, 255, 255));
        btn_ajouter.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_ajouter.setForeground(new java.awt.Color(51, 102, 255));
        btn_ajouter.setText("ajouter");
        btn_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouterActionPerformed(evt);
            }
        });
        panel_utilisateur.add(btn_ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 80, 30));

        btn_modifier.setBackground(new java.awt.Color(255, 255, 255));
        btn_modifier.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_modifier.setForeground(new java.awt.Color(51, 102, 255));
        btn_modifier.setText("modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });
        panel_utilisateur.add(btn_modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 90, 30));

        btn_supprimer.setBackground(new java.awt.Color(255, 255, 255));
        btn_supprimer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_supprimer.setForeground(new java.awt.Color(51, 102, 255));
        btn_supprimer.setText("supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });
        panel_utilisateur.add(btn_supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 100, 30));

        panel_matricule5.setBackground(new java.awt.Color(84, 127, 206));

        jLabel50.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel50.setText("ecart type :");

        javax.swing.GroupLayout panel_matricule5Layout = new javax.swing.GroupLayout(panel_matricule5);
        panel_matricule5.setLayout(panel_matricule5Layout);
        panel_matricule5Layout.setHorizontalGroup(
            panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule5Layout.createSequentialGroup()
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel49)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel45)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel46)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel47))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ecart_type, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule5Layout.setVerticalGroup(
            panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule5Layout.createSequentialGroup()
                .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_matricule5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel50)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule5Layout.createSequentialGroup()
                        .addComponent(txt_ecart_type, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel_utilisateur.add(panel_matricule5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 270, 80));

        panel_matricule10.setBackground(new java.awt.Color(84, 127, 206));

        jLabel72.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel72.setText("moyenne :");

        javax.swing.GroupLayout panel_matricule10Layout = new javax.swing.GroupLayout(panel_matricule10);
        panel_matricule10.setLayout(panel_matricule10Layout);
        panel_matricule10Layout.setHorizontalGroup(
            panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel70)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule10Layout.createSequentialGroup()
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel71)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel67)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel68)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel69))
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_moyenne, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule10Layout.setVerticalGroup(
            panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule10Layout.createSequentialGroup()
                .addGroup(panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule10Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_matricule10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel72)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule10Layout.createSequentialGroup()
                        .addComponent(txt_moyenne, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel_utilisateur.add(panel_matricule10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 270, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        table_vente.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        table_vente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "designation", "quantite", "ecart type", "moyenne"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_vente.setGridColor(new java.awt.Color(255, 255, 255));
        table_vente.setRowHeight(22);
        table_vente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_venteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_vente);

        javax.swing.GroupLayout panel_venteLayout = new javax.swing.GroupLayout(panel_vente);
        panel_vente.setLayout(panel_venteLayout);
        panel_venteLayout.setHorizontalGroup(
            panel_venteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_venteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_venteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_venteLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(txt_date2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_venteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel_venteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_venteLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addGroup(panel_venteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_venteLayout.createSequentialGroup()
                                        .addComponent(txt_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panel_venteLayout.setVerticalGroup(
            panel_venteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_venteLayout.createSequentialGroup()
                .addGap(482, 482, 482)
                .addComponent(txt_date2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(488, 488, 488))
            .addGroup(panel_venteLayout.createSequentialGroup()
                .addGroup(panel_venteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_venteLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel9)
                        .addGap(171, 171, 171)
                        .addGroup(panel_venteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_venteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_vente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_vente, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rechercheActionPerformed

    private void txt_rechercheKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rechercheKeyTyped
       
        
        
            
            txt_recherche.getDocument().addDocumentListener(new DocumentListener(){
            
                @Override
                public void insertUpdate(DocumentEvent de) {
                   System.out.println(" insert  " + txt_recherche.getText());
                   recherche(txt_recherche.getText());
                }

                @Override
                public void removeUpdate(DocumentEvent de) {
                    System.out.println(" update  " + txt_recherche.getText());
                    recherche(txt_recherche.getText());
                }

                @Override
                public void changedUpdate(DocumentEvent de) {
                  System.out.println(" delete  " + txt_recherche.getText());
                  recherche(txt_recherche.getText());
                }
            
                });
            
        
        
    }//GEN-LAST:event_txt_rechercheKeyTyped

    private void btn_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouterActionPerformed
        // btn ajouter

        // btn enregistrer

        // btouon enregistrer ( inserer )

        // btouon enregistrer ( inserer )

        String designation = txt_des.getText();

        String quantite = txt_quantite.getText();

        String ecart_type = txt_ecart_type.getText();

        String moyenne = txt_moyenne.getText();

        String url;
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/ahmed";
            con = DriverManager.getConnection(url,"root","Aminedridi11");
            //  System.out.println("mrigl");

        }
        catch (Exception e) {
            System.out.println(e.toString());
        }

        try {
            // login action

            Statement stm = con.createStatement();

            //execute query

            String sql =" INSERT INTO vente (designation,quantite,ecrattype,moyenne) VALUES ('"+designation+"','"+quantite+"','"+ecart_type+"','"+moyenne+"') " ;

            System.out.println(sql);

            PreparedStatement ps = con.prepareStatement(sql);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,"la vente premiere est ajouté avec succés ");

            // remplir le tab avec nouveau utilisateur

            DefaultTableModel model3 = (DefaultTableModel) table_vente.getModel();

            Object[] table = new Object[4];

            table[0] = designation ;

            table[1] = quantite ;

            table[2] = ecart_type ;

            table[3] = moyenne ;

            model3.addRow(table);

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_btn_ajouterActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
        // btn modifier

        // bouton modifieir

        // modifier utiliateur

        // nom et prenom ne change pas dans la modification

        // modifier user

        String url;
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/ahmed";
            con = DriverManager.getConnection(url,"root","Aminedridi11");
            //  System.out.println("mrigl");

        }
        catch (Exception e) {
            System.out.println(e.toString());
        }

        try {
            // login action

            Statement stm = con.createStatement();

            //execute query

            // input pour l'update celon la matricule

            //UPDATE client SET rue = '49 Rue Ameline',ville = 'Saint-Eustache-la-Forêt',code_postal = '76210' WHERE id = 2

            String sql =" UPDATE vente SET quantite = '"+txt_quantite.getText()+"',ecrattype ='"+txt_ecart_type.getText()+"',moyenne = '"+txt_moyenne.getText()+"' WHERE designation ='"+txt_des.getText()+"' ;" ;

            System.out.println(sql);

            PreparedStatement ps = con.prepareStatement(sql);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,"la vente est modifié avec succés ");

            // ouvrir la page de consulation des utilisateurs

        } catch (SQLException ex) {

            System.out.println(ex.getMessage());

        }
        // modifier le jtable

        int SelectedRowIndex = table_vente.getSelectedRow();

        DefaultTableModel model2 = (DefaultTableModel) table_vente.getModel();
        // effacer la ligne selectionnée

        model2.removeRow(SelectedRowIndex);

        // ajouté la nouvelle ligne

        Object[] table = new Object[4];

        table[0] = txt_des.getText();

        table[1] = txt_quantite.getText();

        table[2] = txt_ecart_type.getText();

        table[3] = txt_moyenne.getText();

        model2.addRow(table);

    }//GEN-LAST:event_btn_modifierActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        // btn supp

        //supp

        String url;
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/ahmed";
            con = DriverManager.getConnection(url,"root","Aminedridi11");
            //  System.out.println("mrigl");

        }
        catch (Exception e) {
            System.out.println(e.toString());
        }

        try {
            // login action

            Statement stm = con.createStatement();

            //execute query

            // input pour l'update celon la matricule

            //UPDATE client SET rue = '49 Rue Ameline',ville = 'Saint-Eustache-la-Forêt',code_postal = '76210' WHERE id = 2

            String sql =" DELETE FROM vente WHERE designation ='"+txt_des.getText()+"'" ;

            System.out.println(sql);

            PreparedStatement ps = con.prepareStatement(sql);

            ps.executeUpdate();

            //   System.out.println("le utilisateur de nom "+nom+" est supprimé !!!  ");

            JOptionPane.showMessageDialog(this,"la vente est supprimé avec succés  ");

        } catch (SQLException ex) {

            System.out.println(ex.getMessage());

        }

        // supprimer la ligne selectionnée dans jtbale

        int SelectedRowIndex = table_vente.getSelectedRow();

        DefaultTableModel model2 = (DefaultTableModel) table_vente.getModel();
        // effacer la ligne selectionnée

        model2.removeRow(SelectedRowIndex);

        //    txt_ref.setText("");  txt_des.setText(""); txt_quantite.setText("");

        txt_ecart_type.setText("");

    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void table_venteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_venteMouseClicked

        // tabel client mouse clicked

        // table mouse clicked

        DefaultTableModel model3 = (DefaultTableModel) table_vente.getModel();

        int SelectedRowIndex = table_vente.getSelectedRow();

        txt_des.setText(model3.getValueAt(SelectedRowIndex, 0).toString());

        txt_quantite.setText(model3.getValueAt(SelectedRowIndex, 1).toString());

        txt_ecart_type.setText(model3.getValueAt(SelectedRowIndex, 2).toString());

        txt_moyenne.setText(model3.getValueAt(SelectedRowIndex, 3).toString());

        //   txt_type.setText(model3.getValueAt(SelectedRowIndex, 3).toString());

    }//GEN-LAST:event_table_venteMouseClicked

    
    
    
     public void recherche(String text){
    
        
        String url;
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/ahmed";
            con = DriverManager.getConnection(url,"root","Aminedridi11");
            //  System.out.println("mrigl");

        }
        catch (Exception e) {
            System.out.println(e.toString());
        }

        try {
            // login action

            Statement stm = con.createStatement();

      
            
            
               // effacer le tab
                
                
                DefaultTableModel dm = (DefaultTableModel) table_vente.getModel();
            int rowCount = dm.getRowCount();
            //Remove rows one by one from the end of the table
            for (int i = rowCount - 1; i >= 0; i--) {
         dm.removeRow(i);
            }
                
            
            
            
            
         
            // check user
            
            ResultSet rs ; 
            
            String sql1 = " SELECT * FROM `vente` WHERE designation like '%"+text+"%' or quantite like '%"+ text +"%' or ecrattype LIKE '%"+text+"%'  or moyenne LIKE '%"+text+"%'   ;"   ;

            System.out.println(sql1);
            
            rs =  stm.executeQuery(sql1);
            
            

            while(rs.next()){
                
             
            
                // remplir le tableau  avec la req select

                
                
                 String designation = rs.getString("designation");
                 
                String quantite = rs.getString("quantite");
          
              String ecarttype = rs.getString("ecrattype");

              
              String moyenne = rs.getString("moyenne");
      
              
             
             
              
                
               // System.out.println(" info === " +  reference  + designation +   prix_unitaire + prix_globale  +   type  );
  

                // remplir le tableau 
                
               
           
       
       Object[] table = new Object[4];
   
               
      table[0] = designation;
       
       table[1] = quantite;

       
       table[2] = ecarttype;  
       
       table[3] = moyenne; 

    
  
       
       dm.addRow(table);
       

            
           
            }
               
    }                                        

        catch(Exception ex){
            System.out.println(ex.getMessage());
        } 
        
        
    
    }
    
    
    
    
    
        
        
        private void remplir_users_tab(){
        
        
        ResultSet rs;
        String url;
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/ahmed";
            con = DriverManager.getConnection(url,"root","Aminedridi11");
            //  System.out.println("mrigl");

        }
        catch (Exception e) {
            System.out.println(e.toString());
        }

        try {
            // login action

            Statement stm = con.createStatement();

      

            rs =  stm.executeQuery("SELECT * FROM `vente`");

            //rs = stm.executeQuery("SELECT * FROM admin");

            while(rs.next()){

                 String designation = rs.getString("designation");
                 
                String quantite = rs.getString("quantite");
          
              String ecarttype = rs.getString("ecrattype");

              
              String moyenne = rs.getString("moyenne");
      
              
             
              

                
             //   System.out.println(nom  + prenom +  + departement + mot_de_passe);
  

                // remplir le tableau 
                
                
                
                 DefaultTableModel model2 = (DefaultTableModel) table_vente.getModel();
                 
       
       Object[] table = new Object[4];
   
               
      table[0] = designation;
       
       table[1] = quantite;

       
       table[2] = ecarttype;  
       
       table[3] = moyenne; 

    
       
       
       model2.addRow(table);
       

            }
        
        }
        
          catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
 
    }  
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_vente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_vente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_vente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_vente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Gestion_vente().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Gestion_vente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajouter;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_supprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPanel panel_matricule10;
    private javax.swing.JPanel panel_matricule4;
    private javax.swing.JPanel panel_matricule5;
    private javax.swing.JPanel panel_matricule8;
    private javax.swing.JPanel panel_utilisateur;
    private javax.swing.JPanel panel_vente;
    private javax.swing.JTable table_vente;
    private javax.swing.JLabel txt_date2;
    private javax.swing.JTextField txt_des;
    private javax.swing.JTextField txt_ecart_type;
    private javax.swing.JTextField txt_moyenne;
    private javax.swing.JTextField txt_quantite;
    private javax.swing.JTextField txt_recherche;
    // End of variables declaration//GEN-END:variables
}
