/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dridi family
 */
public final class Gestion_livraison extends javax.swing.JFrame {

    public JPanel getPanel_livraison() {
        return panel_livraison;
    }

    public void setPanel_livraison(JPanel panel_livraison) {
        this.panel_livraison = panel_livraison;
    }

    /**
     * Creates new form Gestion_livraison
     * @throws java.sql.SQLException
     */
    public Gestion_livraison() throws SQLException {
        initComponents();
        
        fill_combo_designation();
        
        remplir_users_tab();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_livraison = new javax.swing.JPanel();
        txt_date = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_livraison = new javax.swing.JTable();
        txt_recherche = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panel_utilisateur = new javax.swing.JPanel();
        panel_matricule6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txt_num_facture = new javax.swing.JTextField();
        panel_matricule8 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        combo_des2 = new javax.swing.JComboBox<>();
        combo_des3 = new javax.swing.JComboBox<>();
        combo_mp = new javax.swing.JComboBox<>();
        btn_ajouter = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        panel_matricule5 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        combo_date_livraison = new com.toedter.calendar.JDateChooser();
        panel_matricule10 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        combo_des = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_livraison.setBackground(new java.awt.Color(255, 255, 255));

        txt_date.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_date.setForeground(new java.awt.Color(102, 102, 102));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/login.PNG"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/logout.PNG"))); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        table_livraison.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        table_livraison.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "num facture", "methode paiement", "date livraison", "designation article"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_livraison.setGridColor(new java.awt.Color(255, 255, 255));
        table_livraison.setRowHeight(22);
        table_livraison.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_livraisonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_livraison);
        if (table_livraison.getColumnModel().getColumnCount() > 0) {
            table_livraison.getColumnModel().getColumn(0).setResizable(false);
            table_livraison.getColumnModel().getColumn(1).setResizable(false);
        }

        txt_recherche.setBackground(new java.awt.Color(123, 156, 225));
        txt_recherche.setForeground(new java.awt.Color(255, 255, 255));
        txt_recherche.setBorder(null);
        txt_recherche.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_recherche.setPreferredSize(new java.awt.Dimension(2, 20));
        txt_recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rechercheActionPerformed(evt);
            }
        });
        txt_recherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rechercheKeyTyped(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/search-icon.png"))); // NOI18N
        jLabel1.setText("search");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("gestion des utilisateurs");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("gestion des utilisateurs");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 255));
        jLabel7.setText("gestion des livraison");

        panel_utilisateur.setBackground(new java.awt.Color(120, 168, 252));
        panel_utilisateur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_matricule6.setBackground(new java.awt.Color(84, 127, 206));

        jLabel36.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel36.setText("num facture :");

        javax.swing.GroupLayout panel_matricule6Layout = new javax.swing.GroupLayout(panel_matricule6);
        panel_matricule6.setLayout(panel_matricule6Layout);
        panel_matricule6Layout.setHorizontalGroup(
            panel_matricule6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel_matricule6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule6Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_matricule6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panel_matricule6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_matricule6Layout.createSequentialGroup()
                                .addComponent(txt_num_facture, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(jLabel35)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel23)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel24)
                                .addGap(85, 85, 85)
                                .addComponent(jLabel25))
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule6Layout.setVerticalGroup(
            panel_matricule6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addGap(2, 2, 2)
                .addGroup(panel_matricule6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(panel_matricule6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule6Layout.createSequentialGroup()
                        .addComponent(txt_num_facture, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel_utilisateur.add(panel_matricule6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 270, 70));

        panel_matricule8.setBackground(new java.awt.Color(84, 127, 206));

        jLabel54.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel54.setText("methode de paiement :");

        combo_des2.setBackground(new java.awt.Color(0, 22, 51));
        combo_des2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "03 ", "07", "regenérée", "exceed", "souple", "cocaline", "colorant", "divers", "additif", "pp", "inj ", "hd ", "lineaire", " ", " " }));

        combo_des3.setBackground(new java.awt.Color(0, 22, 51));
        combo_des3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "03 ", "07", "regenérée", "exceed", "souple", "cocaline", "colorant", "divers", "additif", "pp", "inj ", "hd ", "lineaire", " ", " " }));

        combo_mp.setBackground(new java.awt.Color(0, 22, 51));
        combo_mp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "en ligne", "espece", " " }));

        javax.swing.GroupLayout panel_matricule8Layout = new javax.swing.GroupLayout(panel_matricule8);
        panel_matricule8.setLayout(panel_matricule8Layout);
        panel_matricule8Layout.setHorizontalGroup(
            panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule8Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_mp, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(215, 215, 215)
                .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel53)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel33)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel34)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel51))
                    .addGroup(panel_matricule8Layout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(270, 270, 270))
            .addGroup(panel_matricule8Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel54)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_matricule8Layout.createSequentialGroup()
                    .addGap(341, 341, 341)
                    .addComponent(combo_des2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(514, Short.MAX_VALUE)))
            .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_matricule8Layout.createSequentialGroup()
                    .addGap(341, 341, 341)
                    .addComponent(combo_des3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(514, Short.MAX_VALUE)))
        );
        panel_matricule8Layout.setVerticalGroup(
            panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule8Layout.createSequentialGroup()
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(combo_mp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_matricule8Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(combo_des2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
            .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_matricule8Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(combo_des3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );

        panel_utilisateur.add(panel_matricule8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 270, 70));

        btn_ajouter.setBackground(new java.awt.Color(255, 255, 255));
        btn_ajouter.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_ajouter.setForeground(new java.awt.Color(51, 102, 255));
        btn_ajouter.setText("ajouter");
        btn_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouterActionPerformed(evt);
            }
        });
        panel_utilisateur.add(btn_ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 80, 30));

        btn_modifier.setBackground(new java.awt.Color(255, 255, 255));
        btn_modifier.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_modifier.setForeground(new java.awt.Color(51, 102, 255));
        btn_modifier.setText("modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });
        panel_utilisateur.add(btn_modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 90, 30));

        btn_supprimer.setBackground(new java.awt.Color(255, 255, 255));
        btn_supprimer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_supprimer.setForeground(new java.awt.Color(51, 102, 255));
        btn_supprimer.setText("supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });
        panel_utilisateur.add(btn_supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 100, 30));

        panel_matricule5.setBackground(new java.awt.Color(84, 127, 206));

        jLabel50.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel50.setText("date livraison :");

        combo_date_livraison.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout panel_matricule5Layout = new javax.swing.GroupLayout(panel_matricule5);
        panel_matricule5.setLayout(panel_matricule5Layout);
        panel_matricule5Layout.setHorizontalGroup(
            panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule5Layout.createSequentialGroup()
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel49)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel45)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel46)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel47))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_date_livraison, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule5Layout.setVerticalGroup(
            panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule5Layout.createSequentialGroup()
                .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_matricule5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel50)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule5Layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(combo_date_livraison, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel_utilisateur.add(panel_matricule5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 270, 80));

        panel_matricule10.setBackground(new java.awt.Color(84, 127, 206));

        jLabel72.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel72.setText("designation article :");

        combo_des.setBackground(new java.awt.Color(0, 22, 51));

        javax.swing.GroupLayout panel_matricule10Layout = new javax.swing.GroupLayout(panel_matricule10);
        panel_matricule10.setLayout(panel_matricule10Layout);
        panel_matricule10Layout.setHorizontalGroup(
            panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel70)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule10Layout.createSequentialGroup()
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel71)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel67)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel68)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel69))
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_des, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule10Layout.setVerticalGroup(
            panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule10Layout.createSequentialGroup()
                .addGroup(panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule10Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_matricule10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel72)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule10Layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(combo_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel_utilisateur.add(panel_matricule10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 270, -1));

        javax.swing.GroupLayout panel_livraisonLayout = new javax.swing.GroupLayout(panel_livraison);
        panel_livraison.setLayout(panel_livraisonLayout);
        panel_livraisonLayout.setHorizontalGroup(
            panel_livraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_livraisonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_livraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_livraisonLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panel_livraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_livraisonLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_livraisonLayout.createSequentialGroup()
                        .addComponent(panel_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel_livraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_livraisonLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_livraisonLayout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(txt_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_livraisonLayout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panel_livraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_livraisonLayout.createSequentialGroup()
                    .addGap(292, 292, 292)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(359, Short.MAX_VALUE)))
            .addGroup(panel_livraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_livraisonLayout.createSequentialGroup()
                    .addGap(245, 245, 245)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(312, Short.MAX_VALUE)))
        );
        panel_livraisonLayout.setVerticalGroup(
            panel_livraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_livraisonLayout.createSequentialGroup()
                .addGroup(panel_livraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_livraisonLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel7)
                        .addGap(158, 158, 158)
                        .addGroup(panel_livraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_livraisonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(242, 242, 242)
                .addComponent(txt_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(499, 499, 499)
                .addGroup(panel_livraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel17))
                .addContainerGap())
            .addGroup(panel_livraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_livraisonLayout.createSequentialGroup()
                    .addGap(648, 648, 648)
                    .addComponent(jLabel2)
                    .addContainerGap(618, Short.MAX_VALUE)))
            .addGroup(panel_livraisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_livraisonLayout.createSequentialGroup()
                    .addGap(648, 648, 648)
                    .addComponent(jLabel5)
                    .addContainerGap(618, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_livraison, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_livraison, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rechercheActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        // btn supprimer
        
        
        
        //supp
        
        
            String url;  
            Connection con = null;  
            try {  
                Class.forName("com.mysql.jdbc.Driver");  
            url="jdbc:mysql://localhost:3306/ahmed";  
                con = DriverManager.getConnection(url,"root","Aminedridi11");  
              //  System.out.println("mrigl");  
              
                }  
                catch (Exception e) {  
                System.out.println(e.toString());  
            }
            
        try {
            // login action
            
            Statement stm = con.createStatement();
            
            //execute query
            
            // input pour l'update celon la matricule
        
            
           String num_facture = txt_num_facture.getText();
           
            
            //UPDATE client SET rue = '49 Rue Ameline',ville = 'Saint-Eustache-la-Forêt',code_postal = '76210' WHERE id = 2
        
              
         String sql =" DELETE FROM livraison WHERE num_facture ='"+num_facture+"'" ;       
         System.out.println(sql);
         
        
         
        PreparedStatement ps = con.prepareStatement(sql);
         
          ps.executeUpdate();
  
         
      //   System.out.println("le utilisateur de nom "+nom+" est supprimé !!!  ");
         
         JOptionPane.showMessageDialog(this,"la livraison est supprimé avec succés  ");
       
       
     
   
        } catch (SQLException ex) {
            
            System.out.println(ex.getMessage());
            
        }
        
        // supprimer la ligne selectionnée dans jtbale
        
         int SelectedRowIndex = table_livraison.getSelectedRow();
            
            
                
                 DefaultTableModel model2 = (DefaultTableModel) table_livraison.getModel();
                 // effacer la ligne selectionnée
                 
                 
                 model2.removeRow(SelectedRowIndex);
                 
                 
        
        
        
    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void btn_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouterActionPerformed
        // btn ajouter
        
        
        // btn enregistrer
        
          // btouon enregistrer ( inserer )
        
          // date format
           
           DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
          
          String num_facture = txt_num_facture.getText();
         
          String methode_paiement = combo_mp.getSelectedItem().toString();
          
          
          String date_de_livraison = df.format( combo_date_livraison.getDate() );
          
       
          
          String designation = combo_des.getSelectedItem().toString();
           
          
           
                  
       String url;  
            Connection con = null;  
            try {  
                Class.forName("com.mysql.jdbc.Driver");  
            url="jdbc:mysql://localhost:3306/ahmed";  
                con = DriverManager.getConnection(url,"root","Aminedridi11");  
              //  System.out.println("mrigl");  
              
                }  
                catch (Exception e) {  
                System.out.println(e.toString());  
            }
            
        try {
            // login action
            
            Statement stm = con.createStatement();
            
            //execute query

         
         String sql =" INSERT INTO livraison (num_facture,methode_paiement,date_livraison,designation_article) VALUES ('"+num_facture+"','"+methode_paiement+"','"+date_de_livraison+"','"+designation+"') " ;       
     
         System.out.println(sql);
      
         
        PreparedStatement ps = con.prepareStatement(sql);
         
          ps.executeUpdate();
  
         
         
         JOptionPane.showMessageDialog(this,"une livraison est ajouté avec succés ");
         
       
       
     
   
       // remplir le tab avec nouveau utilisateur
       
    
                
                 DefaultTableModel model3 = (DefaultTableModel) table_livraison.getModel();
       
                 
                 
       Object[] table = new Object[5];
   
               
      table[0] = num_facture ;
       
       table[1] = methode_paiement ;

       
       table[2] = date_de_livraison ;   
       
          
       table[3] = designation ;  
       
   
       
                 
       
       model3.addRow(table);
       
      
      
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
        
        
        
    
        
        
        
    }//GEN-LAST:event_btn_ajouterActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
        // btn modifier
        
        
            
           DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
          
          String num_facture = txt_num_facture.getText();
         
          String methode_paiement = combo_mp.getSelectedItem().toString();
          
          
          String date_de_livraison = df.format( combo_date_livraison.getDate() );
          
       
          
          String designation = combo_des.getSelectedItem().toString();
           
            String url;  
            Connection con = null;  
            try {  
                Class.forName("com.mysql.jdbc.Driver");  
            url="jdbc:mysql://localhost:3306/ahmed";  
                con = DriverManager.getConnection(url,"root","Aminedridi11");  
              //  System.out.println("mrigl");  
              
                }  
                catch (Exception e) {  
                System.out.println(e.toString());  
            }
            
        try {
            // login action
            
            Statement stm = con.createStatement();
            
            //execute query
            
            // input pour l'update celon la matricule
           
           
            
            //UPDATE client SET rue = '49 Rue Ameline',ville = 'Saint-Eustache-la-Forêt',code_postal = '76210' WHERE id = 2
        
              
         String sql =" UPDATE livraison SET num_facture ='"+num_facture+"',methode_paiement = '"+methode_paiement+"',date_livraison ='"+date_de_livraison+"',designation_article = '"+ designation+"'"+" WHERE num_facture ='"+num_facture+"'"; 
         
         System.out.println(sql);
 
         
        PreparedStatement ps = con.prepareStatement(sql);
         
          ps.executeUpdate();
  
         
         
         
         JOptionPane.showMessageDialog(this,"la livraison est modifié avec succés ");
       
       
     
   
       // ouvrir la page de consulation des utilisateurs 
      
        } catch (SQLException ex) {
          
            System.out.println(ex.getMessage());
            
        }
        // modifier le jtable
        
            int SelectedRowIndex = table_livraison.getSelectedRow();
            
            
                
                 DefaultTableModel model2 = (DefaultTableModel) table_livraison.getModel();
                 // effacer la ligne selectionnée
                 
                 
                 model2.removeRow(SelectedRowIndex);
                 
                 // ajouté la nouvelle ligne
                 
         
       Object[] table = new Object[4] ;
   
               
      table[0] = num_facture ;
       
       table[1] = methode_paiement ;

       
       table[2] = date_de_livraison ;
       
        table[3] = designation  ;
    
       model2.addRow(table);
     
                 
            
        
        
    }//GEN-LAST:event_btn_modifierActionPerformed

    private void table_livraisonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_livraisonMouseClicked
       
        
         
        // tabel client mouse clicked
        
        
         // table mouse clicked
        
        
        DefaultTableModel model3 = (DefaultTableModel) table_livraison.getModel();
        
        int SelectedRowIndex = table_livraison.getSelectedRow();
        
        
        
        txt_num_facture.setText(model3.getValueAt(SelectedRowIndex, 0).toString());
        
        combo_mp.setSelectedItem( model3.getValueAt(SelectedRowIndex, 1).toString() );
        
      
        
       //  txt_quantite.setText(model3.getValueAt(SelectedRowIndex, 2).toString());
       
      // date_lancement.setDate(date);
         
            
           DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        
        try {
            Date d1 = df.parse(model3.getValueAt(SelectedRowIndex, 2).toString());
            
            //  txt_tel.setText(model3.getValueAt(SelectedRowIndex, 2).toString());
            
            combo_date_livraison.setDate(d1);
            
   
            
            
            
            
        } catch (ParseException ex) {
           
            System.out.println(ex.getMessage());
            
            
        }
           combo_des.setSelectedItem( model3.getValueAt(SelectedRowIndex, 3).toString() );  
        
        
    }//GEN-LAST:event_table_livraisonMouseClicked

    private void txt_rechercheKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rechercheKeyTyped
        // key type
        
          
            txt_recherche.getDocument().addDocumentListener(new DocumentListener(){
            
                @Override
                public void insertUpdate(DocumentEvent de) {
                   System.out.println(" insert  " + txt_recherche.getText());
                   recherche(txt_recherche.getText());
                }

                @Override
                public void removeUpdate(DocumentEvent de) {
                    System.out.println(" update  " + txt_recherche.getText());
                    recherche(txt_recherche.getText());
                }

                @Override
                public void changedUpdate(DocumentEvent de) {
                  System.out.println(" delete  " + txt_recherche.getText());
                  recherche(txt_recherche.getText());
                }
            
                });
            
        
        
    }//GEN-LAST:event_txt_rechercheKeyTyped

    
    public void recherche(String text){
    
        
        String url;
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/ahmed";
            con = DriverManager.getConnection(url,"root","Aminedridi11");
            //  System.out.println("mrigl");

        }
        catch (Exception e) {
            System.out.println(e.toString());
        }

        try {
            // login action

            Statement stm = con.createStatement();

      
            
            
               // effacer le tab
                
                
                DefaultTableModel dm = (DefaultTableModel) table_livraison.getModel();
            int rowCount = dm.getRowCount();
            //Remove rows one by one from the end of the table
            for (int i = rowCount - 1; i >= 0; i--) {
         dm.removeRow(i);
            }
                
            
            
            
            
         
            // check user
            
            ResultSet rs ; 
            
            String sql1 = " SELECT * FROM `livraison` WHERE num_facture like '%"+text+"%' or methode_paiement like '%"+ text +"%' or date_livraison LIKE '%"+text+"%'  or designation_article LIKE '%"+text+"%'   ;"   ;

            System.out.println(sql1);
            
            rs =  stm.executeQuery(sql1);
            
            

            while(rs.next()){
                
             
            
                // remplir le tableau  avec la req select

                String num_facture = rs.getString("num_facture");
          
              String methode_paiement = rs.getString("methode_paiement");

              
              String date_livraison = rs.getString("date_livraison");
              
              String designation = rs.getString("designation_article");
              
             
              
                
             //   System.out.println(" info === " +  reference  + designation +   prix_unitaire + prix_globale  +   type  );
  

                // remplir le tableau 
                
               
       
       Object[] table = new Object[4];
   
               
      table[0] = num_facture;
       
       table[1] = methode_paiement;

       
       table[2] = date_livraison;  
       
       table[3] = designation; 
       
    
         
       
  
       
       dm.addRow(table);
       

            
           
            }
               
    }                                        

        catch(Exception ex){
            System.out.println(ex.getMessage());
        } 
        
        
    
    }
    
    
    
      
        public void fill_combo_designation() throws SQLException{
        
        
            
        String url;
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/ahmed";
            con = DriverManager.getConnection(url,"root","Aminedridi11");
            //  System.out.println("mrigl");

        }
        catch (Exception e) {
            System.out.println(e.toString());
        }

            // login action

            Statement stm = con.createStatement();

           
           
            
         
            // check user
            
            ResultSet rs ; 
            
            String sql1 = "SELECT * FROM `article`  ";

            System.out.println(sql1);
            
            rs =  stm.executeQuery(sql1);
            
            

            //rs = stm.executeQuery("SELECT * FROM admin");

            while(rs.next()){
 
  
             combo_des.addItem(rs.getString("designation"));
           
            }
               
            
            
            
        }
    
    
    
    
    
    
        
        private void remplir_users_tab(){
        
        
        ResultSet rs;
        String url;
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/ahmed";
            con = DriverManager.getConnection(url,"root","Aminedridi11");
            //  System.out.println("mrigl");

        }
        catch (Exception e) {
            System.out.println(e.toString());
        }

        try {
            
            // login action

            Statement stm = con.createStatement();

      

            rs =  stm.executeQuery("SELECT * FROM `livraison`");

            //rs = stm.executeQuery("SELECT * FROM admin");

            while(rs.next()){

                String num_facture = rs.getString("num_facture");
              
                   String methode_paiement = rs.getString("methode_paiement");
                   
                   String date_livraison = rs.getString("date_livraison");
                   
                    String designation_article = rs.getString("designation_article");
                  
      
                
                
                
                 DefaultTableModel model2 = (DefaultTableModel) table_livraison.getModel();
       
       Object[] table = new Object[4];
   
            
      table[0] = num_facture ;
       
       table[1] = methode_paiement ;

       
       table[2] = date_livraison ;   
       
          
       table[3] = designation_article ;  
       
      
       
       
       
       model2.addRow(table);
       

            }
        
        }
        
          catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
 
    }
        
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_livraison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Gestion_livraison().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Gestion_livraison.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajouter;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_supprimer;
    private com.toedter.calendar.JDateChooser combo_date_livraison;
    private javax.swing.JComboBox<String> combo_des;
    private javax.swing.JComboBox<String> combo_des2;
    private javax.swing.JComboBox<String> combo_des3;
    private javax.swing.JComboBox<String> combo_mp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel panel_livraison;
    private javax.swing.JPanel panel_matricule10;
    private javax.swing.JPanel panel_matricule5;
    private javax.swing.JPanel panel_matricule6;
    private javax.swing.JPanel panel_matricule8;
    private javax.swing.JPanel panel_utilisateur;
    private javax.swing.JTable table_livraison;
    private javax.swing.JLabel txt_date;
    private javax.swing.JTextField txt_num_facture;
    private javax.swing.JTextField txt_recherche;
    // End of variables declaration//GEN-END:variables
}
