/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package swing;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author dridi family
 */
public class Modifier_pic extends javax.swing.JFrame {

    /** Creates new form Modifier_pic */
    public Modifier_pic(int id ,String titre ,String mois1 , String mois2 , String mois3 , String mois4 ,String mois5 , String mois6 ,String mois7 , String mois8 , String mois9 ,String mois10 ,String mois11,String mois12) {
        initComponents();
        
        this.setTitle(titre);
        
        lbl_titre.setText("");
        
        lbl_titre.setText(titre);
        
        txt_mois1.setText(mois1);
        
        txt_mois2.setText(mois2);
        
        txt_mois3.setText(mois3);
        
        txt_mois4.setText(mois4);
        
        txt_mois5.setText(mois5);
        
        txt_mois6.setText(mois6);
        
        txt_mois7.setText(mois7);
        
        txt_mois8.setText(mois8);
        
        txt_mois9.setText(mois9);
        
        txt_mois10.setText(mois10);
        
         txt_mois11.setText(mois11);
         
          txt_mois12.setText(mois12);
          
          lbl_id.setText(String.valueOf(id));
          
          lbl_id.setVisible(false);
          
          lbl_title.setText(titre);
          
          lbl_title.setVisible(false);
        
    }

    private Modifier_pic() {
           initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_ajouter_machine = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        txt_mois1 = new javax.swing.JTextField();
        txt_3 = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        txt_mois2 = new javax.swing.JTextField();
        txt_4 = new javax.swing.JLabel();
        panel_matricule6 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        txt_mois3 = new javax.swing.JTextField();
        txt_9 = new javax.swing.JLabel();
        panel_matricule8 = new javax.swing.JPanel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        txt_mois4 = new javax.swing.JTextField();
        txt_15 = new javax.swing.JLabel();
        lbl_titre = new javax.swing.JLabel();
        panel_matricule9 = new javax.swing.JPanel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        txt_mois5 = new javax.swing.JTextField();
        txt_16 = new javax.swing.JLabel();
        panel_matricule16 = new javax.swing.JPanel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        txt_mois10 = new javax.swing.JTextField();
        txt_23 = new javax.swing.JLabel();
        panel_matricule11 = new javax.swing.JPanel();
        jLabel113 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        txt_mois9 = new javax.swing.JTextField();
        txt_18 = new javax.swing.JLabel();
        panel5 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        txt_mois6 = new javax.swing.JTextField();
        txt_5 = new javax.swing.JLabel();
        panel6 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        txt_mois7 = new javax.swing.JTextField();
        txt_6 = new javax.swing.JLabel();
        panel_matricule7 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        txt_mois8 = new javax.swing.JTextField();
        txt_10 = new javax.swing.JLabel();
        panel_matricule17 = new javax.swing.JPanel();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        txt_mois11 = new javax.swing.JTextField();
        txt_24 = new javax.swing.JLabel();
        panel_matricule18 = new javax.swing.JPanel();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        txt_mois12 = new javax.swing.JTextField();
        txt_25 = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        btn_ajouter_machine.setBackground(new java.awt.Color(51, 0, 51));
        btn_ajouter_machine.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_ajouter_machine.setText(" modifier ");
        btn_ajouter_machine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouter_machineActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/cancel_icon.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        panel3.setBackground(new java.awt.Color(51, 0, 51));

        txt_mois1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mois1ActionPerformed(evt);
            }
        });

        txt_3.setBackground(new java.awt.Color(51, 0, 51));
        txt_3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_3.setForeground(new java.awt.Color(255, 255, 255));
        txt_3.setText("mois 1  :");
        txt_3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_3ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel72)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_3, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(txt_mois1))
                .addGap(35, 35, 35)
                .addComponent(jLabel73)
                .addGap(28, 28, 28)
                .addComponent(jLabel54)
                .addGap(45, 45, 45)
                .addComponent(jLabel60)
                .addGap(85, 85, 85)
                .addComponent(jLabel66)
                .addContainerGap())
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addComponent(txt_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_mois1)
                .addContainerGap())
        );

        panel4.setBackground(new java.awt.Color(51, 0, 51));

        txt_4.setBackground(new java.awt.Color(51, 0, 51));
        txt_4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_4.setForeground(new java.awt.Color(255, 255, 255));
        txt_4.setText("mois 2 :");
        txt_4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_4ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel77)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_4, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(txt_mois2))
                .addGap(35, 35, 35)
                .addComponent(jLabel78)
                .addGap(28, 28, 28)
                .addComponent(jLabel74)
                .addGap(45, 45, 45)
                .addComponent(jLabel75)
                .addGap(85, 85, 85)
                .addComponent(jLabel76)
                .addContainerGap())
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel76, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel75, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel78, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel77, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addComponent(txt_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_mois2)
                .addGap(6, 6, 6))
        );

        panel_matricule6.setBackground(new java.awt.Color(51, 0, 51));

        txt_mois3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mois3ActionPerformed(evt);
            }
        });

        txt_9.setBackground(new java.awt.Color(51, 0, 51));
        txt_9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_9.setForeground(new java.awt.Color(255, 255, 255));
        txt_9.setText("mois 3  :");
        txt_9.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_9ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel_matricule6Layout = new javax.swing.GroupLayout(panel_matricule6);
        panel_matricule6.setLayout(panel_matricule6Layout);
        panel_matricule6Layout.setHorizontalGroup(
            panel_matricule6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel92)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule6Layout.createSequentialGroup()
                        .addComponent(txt_mois3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel93)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel84)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel90)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel91))
                    .addComponent(txt_9, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule6Layout.setVerticalGroup(
            panel_matricule6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_matricule6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel91, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel90, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel84, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel93, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel92, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_matricule6Layout.createSequentialGroup()
                .addComponent(txt_9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_mois3)
                .addGap(6, 6, 6))
        );

        panel_matricule8.setBackground(new java.awt.Color(51, 0, 51));

        txt_15.setBackground(new java.awt.Color(51, 0, 51));
        txt_15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_15.setForeground(new java.awt.Color(255, 255, 255));
        txt_15.setText("mois 4 :");
        txt_15.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_15ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel_matricule8Layout = new javax.swing.GroupLayout(panel_matricule8);
        panel_matricule8.setLayout(panel_matricule8Layout);
        panel_matricule8Layout.setHorizontalGroup(
            panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel97)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule8Layout.createSequentialGroup()
                        .addComponent(txt_mois4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel98)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel94)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel95))
                    .addComponent(txt_15, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(jLabel96)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule8Layout.setVerticalGroup(
            panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel96, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel95, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel94, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel98, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel97, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_matricule8Layout.createSequentialGroup()
                .addComponent(txt_15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_mois4)
                .addGap(9, 9, 9))
        );

        lbl_titre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_titre.setForeground(new java.awt.Color(51, 0, 51));

        panel_matricule9.setBackground(new java.awt.Color(51, 0, 51));

        txt_16.setBackground(new java.awt.Color(51, 0, 51));
        txt_16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_16.setForeground(new java.awt.Color(255, 255, 255));
        txt_16.setText("mois 5 :");
        txt_16.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_16ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel_matricule9Layout = new javax.swing.GroupLayout(panel_matricule9);
        panel_matricule9.setLayout(panel_matricule9Layout);
        panel_matricule9Layout.setHorizontalGroup(
            panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel102)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule9Layout.createSequentialGroup()
                        .addComponent(txt_mois5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel103)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel99)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel100))
                    .addComponent(txt_16, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(jLabel101)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule9Layout.setVerticalGroup(
            panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule9Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel99, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel103, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel102, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_matricule9Layout.createSequentialGroup()
                .addComponent(txt_16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_mois5)
                .addContainerGap())
        );

        panel_matricule16.setBackground(new java.awt.Color(51, 0, 51));

        txt_23.setBackground(new java.awt.Color(51, 0, 51));
        txt_23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_23.setForeground(new java.awt.Color(255, 255, 255));
        txt_23.setText("mois 10 :");
        txt_23.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_23ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel_matricule16Layout = new javax.swing.GroupLayout(panel_matricule16);
        panel_matricule16.setLayout(panel_matricule16Layout);
        panel_matricule16Layout.setHorizontalGroup(
            panel_matricule16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule16Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel141)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule16Layout.createSequentialGroup()
                        .addComponent(txt_mois10, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel142)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel138)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel139))
                    .addComponent(txt_23, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(jLabel140)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule16Layout.setVerticalGroup(
            panel_matricule16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule16Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panel_matricule16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel140, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel139, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel138, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel142, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel141, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_matricule16Layout.createSequentialGroup()
                .addComponent(txt_23, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_mois10)
                .addGap(6, 6, 6))
        );

        panel_matricule11.setBackground(new java.awt.Color(51, 0, 51));

        txt_18.setBackground(new java.awt.Color(51, 0, 51));
        txt_18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_18.setForeground(new java.awt.Color(255, 255, 255));
        txt_18.setText("mois 9 :");
        txt_18.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_18ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel_matricule11Layout = new javax.swing.GroupLayout(panel_matricule11);
        panel_matricule11.setLayout(panel_matricule11Layout);
        panel_matricule11Layout.setHorizontalGroup(
            panel_matricule11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule11Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel136)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule11Layout.createSequentialGroup()
                        .addComponent(txt_mois9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel137)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel113)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel134))
                    .addComponent(txt_18, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(jLabel135)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule11Layout.setVerticalGroup(
            panel_matricule11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule11Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panel_matricule11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel135, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel134, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel113, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel137, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel136, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_matricule11Layout.createSequentialGroup()
                .addComponent(txt_18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_mois9)
                .addContainerGap())
        );

        panel5.setBackground(new java.awt.Color(51, 0, 51));

        txt_mois6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mois6ActionPerformed(evt);
            }
        });

        txt_5.setBackground(new java.awt.Color(51, 0, 51));
        txt_5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_5.setForeground(new java.awt.Color(255, 255, 255));
        txt_5.setText("mois 6  :");
        txt_5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_5ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel79)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_5, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(txt_mois6))
                .addGap(35, 35, 35)
                .addComponent(jLabel80)
                .addGap(28, 28, 28)
                .addComponent(jLabel55)
                .addGap(45, 45, 45)
                .addComponent(jLabel61)
                .addGap(85, 85, 85)
                .addComponent(jLabel67)
                .addContainerGap())
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel79, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel5Layout.createSequentialGroup()
                .addComponent(txt_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_mois6)
                .addContainerGap())
        );

        panel6.setBackground(new java.awt.Color(51, 0, 51));

        txt_6.setBackground(new java.awt.Color(51, 0, 51));
        txt_6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_6.setForeground(new java.awt.Color(255, 255, 255));
        txt_6.setText("mois 7 :");
        txt_6.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_6ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel85)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_6, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(txt_mois7))
                .addGap(35, 35, 35)
                .addComponent(jLabel86)
                .addGap(28, 28, 28)
                .addComponent(jLabel81)
                .addGap(45, 45, 45)
                .addComponent(jLabel82)
                .addGap(85, 85, 85)
                .addComponent(jLabel83)
                .addContainerGap())
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel82, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel81, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel86, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel85, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                .addComponent(txt_6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_mois7)
                .addGap(6, 6, 6))
        );

        panel_matricule7.setBackground(new java.awt.Color(51, 0, 51));

        txt_mois8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mois8ActionPerformed(evt);
            }
        });

        txt_10.setBackground(new java.awt.Color(51, 0, 51));
        txt_10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_10.setForeground(new java.awt.Color(255, 255, 255));
        txt_10.setText("mois 8  :");
        txt_10.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_10ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel_matricule7Layout = new javax.swing.GroupLayout(panel_matricule7);
        panel_matricule7.setLayout(panel_matricule7Layout);
        panel_matricule7Layout.setHorizontalGroup(
            panel_matricule7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel111)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule7Layout.createSequentialGroup()
                        .addComponent(txt_mois8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel112)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel87)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel109)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel110))
                    .addComponent(txt_10, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule7Layout.setVerticalGroup(
            panel_matricule7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_matricule7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel110, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel109, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel87, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel112, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_matricule7Layout.createSequentialGroup()
                .addComponent(txt_10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_mois8)
                .addGap(6, 6, 6))
        );

        panel_matricule17.setBackground(new java.awt.Color(51, 0, 51));

        txt_24.setBackground(new java.awt.Color(51, 0, 51));
        txt_24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_24.setForeground(new java.awt.Color(255, 255, 255));
        txt_24.setText("mois 11 :");
        txt_24.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_24ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel_matricule17Layout = new javax.swing.GroupLayout(panel_matricule17);
        panel_matricule17.setLayout(panel_matricule17Layout);
        panel_matricule17Layout.setHorizontalGroup(
            panel_matricule17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule17Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel146)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule17Layout.createSequentialGroup()
                        .addComponent(txt_mois11, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel147)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel143)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel144))
                    .addComponent(txt_24, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(jLabel145)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule17Layout.setVerticalGroup(
            panel_matricule17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule17Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panel_matricule17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel145, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel144, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel143, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel147, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel146, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_matricule17Layout.createSequentialGroup()
                .addComponent(txt_24, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_mois11)
                .addGap(9, 9, 9))
        );

        panel_matricule18.setBackground(new java.awt.Color(51, 0, 51));

        txt_25.setBackground(new java.awt.Color(51, 0, 51));
        txt_25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_25.setForeground(new java.awt.Color(255, 255, 255));
        txt_25.setText("mois 12 :");
        txt_25.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                txt_25ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel_matricule18Layout = new javax.swing.GroupLayout(panel_matricule18);
        panel_matricule18.setLayout(panel_matricule18Layout);
        panel_matricule18Layout.setHorizontalGroup(
            panel_matricule18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule18Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel151)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule18Layout.createSequentialGroup()
                        .addComponent(txt_mois12, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel152)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel148)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel149))
                    .addComponent(txt_25, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(jLabel150)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_matricule18Layout.setVerticalGroup(
            panel_matricule18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule18Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panel_matricule18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel150, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel149, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel148, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel152, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jLabel151, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_matricule18Layout.createSequentialGroup()
                .addComponent(txt_25, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_mois12)
                .addContainerGap())
        );

        lbl_id.setForeground(new java.awt.Color(204, 0, 0));
        lbl_id.setText("id = ");

        lbl_title.setForeground(new java.awt.Color(204, 0, 0));
        lbl_title.setText("titre = ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panel_matricule6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panel_matricule8, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panel_matricule9, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(259, 259, 259)
                                .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panel_matricule7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panel_matricule11, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panel_matricule16, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(panel_matricule17, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panel_matricule18, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(btn_ajouter_machine, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id)
                    .addComponent(lbl_title))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_matricule6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_matricule8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_matricule9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(panel_matricule17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel_matricule18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_matricule7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_matricule11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_matricule16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(btn_ajouter_machine, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 947, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ajouter_machineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouter_machineActionPerformed
        System.out.println("ajouter pic");

        System.out.println("id = " + lbl_id.getText());
        
        System.out.println("titre = " + lbl_title.getText().substring(10)  );
        
        int id = Integer.parseInt(lbl_id.getText());
        
        String titre = lbl_title.getText().substring(10);
        
        modifier_pic(id,titre);
        
        
    }//GEN-LAST:event_btn_ajouter_machineActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void txt_mois1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mois1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mois1ActionPerformed

    private void txt_3ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_3ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_3ComponentResized

    private void txt_4ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_4ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_4ComponentResized

    private void txt_mois3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mois3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mois3ActionPerformed

    private void txt_9ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_9ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_9ComponentResized

    private void txt_15ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_15ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_15ComponentResized

    private void txt_16ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_16ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_16ComponentResized

    private void txt_mois6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mois6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mois6ActionPerformed

    private void txt_5ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_5ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_5ComponentResized

    private void txt_6ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_6ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_6ComponentResized

    private void txt_mois8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mois8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mois8ActionPerformed

    private void txt_10ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_10ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_10ComponentResized

    private void txt_18ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_18ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_18ComponentResized

    private void txt_23ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_23ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_23ComponentResized

    private void txt_24ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_24ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_24ComponentResized

    private void txt_25ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_25ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_25ComponentResized

    
    
     
        // modifier utiliateur 
        
        // nom et prenom ne change pas dans la modification
        
        // modifier user
        
    
    public void modifier_pic(int id , String titre){
            String url;  
            Connection con = null;  
            try {  
                Class.forName("com.mysql.jdbc.Driver");  
            url="jdbc:mysql://localhost:3306/pic";  
                con = DriverManager.getConnection(url,"root","Aminedridi11");  
              //  System.out.println("mrigl");  
              
                }  
                catch (Exception e) {  
                System.out.println(e.toString());  
            }
            
        try {
            // login action
            
            Statement stm = con.createStatement();
            
            //execute query
            
            // input pour l'update celon la matricule
           
            
                String mois1 = txt_mois1.getText();
              
                   String mois2 = txt_mois2.getText();
                   
                   String mois3 = txt_mois3.getText();
                   
                    String mois4 = txt_mois4.getText();
                    
                    String mois5 = txt_mois5.getText();
                    
                  String mois6 = txt_mois6.getText();
                  
                  String mois7 = txt_mois7.getText();
                  
                  String mois8 = txt_mois8.getText();
                  
                  String mois9 = txt_mois9.getText();
                  
                  String mois10 = txt_mois10.getText();
                  
                  String mois11 = txt_mois11.getText();
          
                   String mois12 = txt_mois12.getText();
                
                  
      
            
            //UPDATE client SET rue = '49 Rue Ameline',ville = 'Saint-Eustache-la-Forêt',code_postal = '76210' WHERE id = 2
        
           
            
            
                 String sql =" UPDATE "+titre+" SET mois1 ='"+mois1+"',mois2 = '"+mois2+"',mois3 =' " + mois3 +"' , mois4 ='"+mois4+"' , mois5 = '"+mois5+"',mois6 = '"+mois6+"',mois7 = '"+mois7+"',mois8 ='"+mois8+"',mois9 = '"+mois9+"',mois10 ='"+mois10+"',mois11 = '"+mois11+"',mois12 ='"+mois12+"'" +" WHERE id ="+id+";"; 
         
         System.out.println(sql);
 
         
        PreparedStatement ps = con.prepareStatement(sql);
         
          ps.executeUpdate();
  
         
           
         JOptionPane.showMessageDialog(this,"le "+titre+" est modifié avec succés ");
            
            
            
           
            
        
      
       
       
     
   
       // ouvrir la page de consulation des utilisateurs 
      
        } catch (SQLException ex) {
          
            System.out.println(ex.getMessage());
            
        }
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modifier_pic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modifier_pic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modifier_pic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modifier_pic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modifier_pic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajouter_machine;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_titre;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JPanel panel6;
    private javax.swing.JPanel panel_matricule11;
    private javax.swing.JPanel panel_matricule16;
    private javax.swing.JPanel panel_matricule17;
    private javax.swing.JPanel panel_matricule18;
    private javax.swing.JPanel panel_matricule6;
    private javax.swing.JPanel panel_matricule7;
    private javax.swing.JPanel panel_matricule8;
    private javax.swing.JPanel panel_matricule9;
    private javax.swing.JLabel txt_10;
    private javax.swing.JLabel txt_15;
    private javax.swing.JLabel txt_16;
    private javax.swing.JLabel txt_18;
    private javax.swing.JLabel txt_23;
    private javax.swing.JLabel txt_24;
    private javax.swing.JLabel txt_25;
    private javax.swing.JLabel txt_3;
    private javax.swing.JLabel txt_4;
    private javax.swing.JLabel txt_5;
    private javax.swing.JLabel txt_6;
    private javax.swing.JLabel txt_9;
    private javax.swing.JTextField txt_mois1;
    private javax.swing.JTextField txt_mois10;
    private javax.swing.JTextField txt_mois11;
    private javax.swing.JTextField txt_mois12;
    private javax.swing.JTextField txt_mois2;
    private javax.swing.JTextField txt_mois3;
    private javax.swing.JTextField txt_mois4;
    private javax.swing.JTextField txt_mois5;
    private javax.swing.JTextField txt_mois6;
    private javax.swing.JTextField txt_mois7;
    private javax.swing.JTextField txt_mois8;
    private javax.swing.JTextField txt_mois9;
    // End of variables declaration//GEN-END:variables

}
