/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dridi family
 */
public class Pdp extends javax.swing.JFrame {

    /**
     * Creates new form Pdp
     */
    public Pdp() {
        initComponents();
       
        remplir_pdp();
        
        this.setTitle("consulter la liste de pdp");
                        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_pic = new javax.swing.JPanel();
        txt_date = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        table_pdp = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_pic.setBackground(new java.awt.Color(255, 255, 255));

        txt_date.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txt_date.setForeground(new java.awt.Color(102, 102, 102));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/login.PNG"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/logout.PNG"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 255));
        jLabel7.setText(" PDP");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/cancel_icon.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jScrollPane6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        table_pdp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        table_pdp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "w+3", "w+4", "w+5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_pdp.setGridColor(new java.awt.Color(255, 255, 255));
        table_pdp.setRowHeight(22);
        table_pdp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_pdpMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(table_pdp);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/add_icon.png"))); // NOI18N
        jLabel8.setText(" ajouter un pdp");

        javax.swing.GroupLayout panel_picLayout = new javax.swing.GroupLayout(panel_pic);
        panel_pic.setLayout(panel_picLayout);
        panel_picLayout.setHorizontalGroup(
            panel_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_picLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_picLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_picLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
            .addGroup(panel_picLayout.createSequentialGroup()
                .addGap(540, 540, 540)
                .addComponent(jLabel12)
                .addContainerGap(581, Short.MAX_VALUE))
            .addGroup(panel_picLayout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        panel_picLayout.setVerticalGroup(
            panel_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_picLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panel_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel12)
                .addGap(2169, 2169, 2169)
                .addComponent(txt_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(499, 499, 499)
                .addGroup(panel_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel17))
                .addContainerGap())
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void table_pdpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_pdpMouseClicked
        // table pdp click mouse
        
          
        DefaultTableModel model3 = (DefaultTableModel) table_pdp.getModel();
        
        int SelectedRowIndex = table_pdp.getSelectedRow();
        
        String mois1 = model3.getValueAt(SelectedRowIndex, 1).toString();
        
        String mois2 = model3.getValueAt(SelectedRowIndex, 2).toString();
        
        String mois3 = model3.getValueAt(SelectedRowIndex, 3).toString();
        
        String mois4 = model3.getValueAt(SelectedRowIndex, 4).toString();
        
        String mois5 = model3.getValueAt(SelectedRowIndex, 5).toString();
        
        String mois6 = model3.getValueAt(SelectedRowIndex, 6).toString();
        
        String mois7 = model3.getValueAt(SelectedRowIndex, 7).toString();
        
        String mois8 = model3.getValueAt(SelectedRowIndex, 8).toString();
        
        String mois9 = model3.getValueAt(SelectedRowIndex, 9).toString();
        
         String mois10 = model3.getValueAt(SelectedRowIndex, 10).toString();
         
          String mois11 = model3.getValueAt(SelectedRowIndex, 11).toString();
          
           String mois12 = model3.getValueAt(SelectedRowIndex, 12).toString();
           
           String mois13 =  model3.getValueAt(SelectedRowIndex, 13).toString();
           
        
             String mois14 =  model3.getValueAt(SelectedRowIndex, 14).toString();
             
               String mois15 =  model3.getValueAt(SelectedRowIndex, 15).toString();
               
                String mois16 =  model3.getValueAt(SelectedRowIndex, 16).toString();
                
                 String mois17 =  model3.getValueAt(SelectedRowIndex, 17).toString();
                 
                  String mois18 =  model3.getValueAt(SelectedRowIndex, 18).toString();
                  
                   String mois19 =  model3.getValueAt(SelectedRowIndex, 19).toString();
                   
                    String mois20 =  model3.getValueAt(SelectedRowIndex, 20).toString();
                    
                     String mois21 =  model3.getValueAt(SelectedRowIndex, 21).toString();
                     
                     String week3 =  model3.getValueAt(SelectedRowIndex, 22).toString();
                     
                     String week4 =  model3.getValueAt(SelectedRowIndex, 23).toString();
                     
                     String week5 =  model3.getValueAt(SelectedRowIndex, 24).toString();
                  
               
                     System.out.println("jour 1 = " +  model3.getValueAt(SelectedRowIndex, 1).toString()  );
                     
                      System.out.println("jour 2 = " +  model3.getValueAt(SelectedRowIndex, 2).toString()  );
                      
                       System.out.println("jour 3 = " +  model3.getValueAt(SelectedRowIndex, 3).toString()  );
                       
                        System.out.println("jour 4 = " +  model3.getValueAt(SelectedRowIndex, 4).toString()  );
                        
                         System.out.println("jour 5 = " +  model3.getValueAt(SelectedRowIndex, 5).toString()  );
                         
                          System.out.println("jour 6 = " +  model3.getValueAt(SelectedRowIndex, 6).toString()  );
                      
               
               
               Consulter_pdp pdp = new Consulter_pdp(mois1,mois2,mois3,mois4,mois5,mois6,mois7,mois8,mois9,mois10,mois11,mois12,mois13,mois14,mois15,mois16,mois17,mois18,mois19,mois20,mois21,week3,week4,week5);
               
           // Consulter_pdp pdp = new Consulter_pdp();
            
               pdp.setVisible(true);
        
    }//GEN-LAST:event_table_pdpMouseClicked

    
    
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
           
        
        //remplir table pdp
        
        private void remplir_pdp(){
        
        
        ResultSet rs;
        String url;
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/pdp";
            con = DriverManager.getConnection(url,"root","Aminedridi11");
            //  System.out.println("mrigl");

        }
        catch (Exception e) {
            System.out.println(e.toString());
        }

        try {
            
            // login action

            Statement stm = con.createStatement();

      

            rs =  stm.executeQuery("SELECT * FROM `produit` ;");

            //les  8 -> 14 premieres lignes

            while(rs.next()){
                        
                
                        String jour1 = rs.getString("jour1");
                        
                         String jour2 = rs.getString("jour2");
                         
                          String jour3 = rs.getString("jour3");
                          
                           String jour4 = rs.getString("jour4");
                           
                            String jour5 = rs.getString("jour5");
                            
                             String jour6 = rs.getString("jour6");
                             
                              String jour7 = rs.getString("jour7");
                              
                               String jour8 = rs.getString("jour8");
                               
                                String jour9 = rs.getString("jour9");
                                
                                 String jour10 = rs.getString("jour10");
                                 
                                  String jour11 = rs.getString("jour11");
                                  
                                   String jour12 = rs.getString("jour12");
                                   
                                    String jour13 = rs.getString("jour13");
                                    
                                      String jour14 = rs.getString("jour14");
                                      
                                        String jour15 = rs.getString("jour15");
                                        
                                          String jour16 = rs.getString("jour16");
                                          
                                            String jour17 = rs.getString("jour17");
                                            
                                              String jour18 = rs.getString("jour18");
                                              
                                               String jour19 = rs.getString("jour19");
                                               
                                                String jour20 = rs.getString("jour20");
                                                
                                                 String jour21 = rs.getString("jour21");
                                                 
                                                  String week3 = rs.getString("week3");
                                                  
                                                   String week4 = rs.getString("week4");
                                                   
                                                    String week5 = rs.getString("week5");
                                                    
                                                    
                                                    
                                                    
                                String id = rs.getString("id");
                                
                                System.out.println("id = " + id );
                              
                    
                 DefaultTableModel model2 = (DefaultTableModel) table_pdp.getModel();
       
       Object[] table = new Object[25];
   
       if(Integer.parseInt(id) == 1 ){
        table[0] = "prevision" ;
       }
       
       if(Integer.parseInt(id) == 2 ){
        table[0] = "besoin" ;
       }
       
       if(Integer.parseInt(id) == 3 ){
        table[0] = "commande ferme" ;
       }
       
       if(Integer.parseInt(id) == 4 ){
        table[0] = "commande previsionnelle" ;
       }
       
       if(Integer.parseInt(id) == 5 ){
        table[0] = "projet_of_debut" ;
       }
       
       if(Integer.parseInt(id) == 6 ){
        table[0] = "projet_of_fin" ;
       }
       
       if(Integer.parseInt(id) == 7 ){
        table[0] = "disponible_vendre" ;
       }
            
     
       
       table[1] = jour1;
  
       table[2] = jour2 ;   
       
       table[3] = jour3 ;
       
       table[4] = jour4;

       table[5] = jour5;
       
       table[6] = jour6;
       
       table[7] = jour7 ;
       
        table[8] = jour8 ;
        
         table[9] = jour9 ;
         
          table[10] = jour10 ;
          
           table[11] = jour11 ;
           
            table[12] = jour12 ;
            
             table[13] = jour13 ;
             
              table[14] = jour14 ;
              
               table[15] = jour15 ;
               
                table[16] = jour16 ;
                
                 table[17] = jour17 ;
                 
                  table[18] = jour18 ;
                  
                   table[19] = jour19 ;
                   
                    table[20] = jour20 ;
                    
                     table[21] = jour21 ;
                     
                      table[22] = week3 ;
       
                       table[23] = week4 ;
                       
                        table[24] = week5 ;

       
       model2.addRow(table);
       

            }
        
        }
        
          catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
 
    }
    
    
        
        
        
        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pdp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pdp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pdp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pdp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pdp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel panel_pic;
    private javax.swing.JTable table_pdp;
    private javax.swing.JLabel txt_date;
    // End of variables declaration//GEN-END:variables
}
