
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.function.Predicate;
import javafx.collections.transformation.FilteredList;
import javafx.collections.transformation.SortedList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dridi family
 */
public class Gestion_utilisateur extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_utilisateur
     */
    public Gestion_utilisateur(String nom , String prenom) {
        initComponents();
       
        
        txt_nom_admin.setText(nom +"  "+prenom);
        
        this.setTitle(" Gestion des utilisateurs ");
        
        remplir_users_tab();
      
    }

    private Gestion_utilisateur() {
           initComponents();
    }


    public JPanel getPanel_gestion_utilisateur() {
        return panel_gestion_utilisateur;
    }

    public void setPanel_gestion_utilisateur(JPanel panel_gestion_utilisateur) {
        this.panel_gestion_utilisateur = panel_gestion_utilisateur;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_logout = new javax.swing.JLabel();
        panel_gestion_utilisateur = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panel_utilisateur = new javax.swing.JPanel();
        panel_matricule4 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txt_mdp = new javax.swing.JPasswordField();
        panel_matricule6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txt_prenom = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        panel_matricule7 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        panel_matricule8 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        txt_adresse_mail = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        panel_matricule5 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        combo_role = new javax.swing.JComboBox<>();
        btn_ajouter = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        panel_matricule9 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        txt_matricule = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_utilisateur = new javax.swing.JTable();
        log_out = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_recherche = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nom_admin = new javax.swing.JLabel();
        label_bulle = new javax.swing.JLabel();

        button1.setBackground(new java.awt.Color(71, 120, 197));
        button1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Book");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12/1/2018", "Expresso POS", "Kenya", null},
                {"12/1/2018", "ROM Gen", "US", null},
                {"12/1/2018", "Text Ed", "UK", null},
                {"12/1/2018", "Mola Con", "China", null}
            },
            new String [] {
                "Date", "Item", "Location", "Completed"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(22);
        jScrollPane1.setViewportView(jTable1);

        lbl_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.PNG"))); // NOI18N
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel_gestion_utilisateur.setBackground(new java.awt.Color(255, 255, 255));
        panel_gestion_utilisateur.setMaximumSize(new java.awt.Dimension(500, 500));
        panel_gestion_utilisateur.setMinimumSize(new java.awt.Dimension(500, 500));
        panel_gestion_utilisateur.setPreferredSize(new java.awt.Dimension(500, 500));

        panel_utilisateur.setBackground(new java.awt.Color(120, 168, 252));
        panel_utilisateur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_matricule4.setBackground(new java.awt.Color(84, 127, 206));

        jLabel44.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel44.setText("mot de passe :");

        javax.swing.GroupLayout panel_matricule4Layout = new javax.swing.GroupLayout(panel_matricule4);
        panel_matricule4.setLayout(panel_matricule4Layout);
        panel_matricule4Layout.setHorizontalGroup(
            panel_matricule4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule4Layout.createSequentialGroup()
                        .addComponent(txt_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel43)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel39)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel40)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel41))
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panel_matricule4Layout.setVerticalGroup(
            panel_matricule4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule4Layout.createSequentialGroup()
                .addComponent(jLabel44)
                .addGap(11, 11, 11)
                .addGroup(panel_matricule4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule4Layout.createSequentialGroup()
                        .addGroup(panel_matricule4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_matricule4Layout.createSequentialGroup()
                        .addComponent(txt_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        panel_utilisateur.add(panel_matricule4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 270, 70));

        panel_matricule6.setBackground(new java.awt.Color(84, 127, 206));

        jLabel36.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel36.setText("prenom :");

        javax.swing.GroupLayout panel_matricule6Layout = new javax.swing.GroupLayout(panel_matricule6);
        panel_matricule6.setLayout(panel_matricule6Layout);
        panel_matricule6Layout.setHorizontalGroup(
            panel_matricule6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel_matricule6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule6Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_matricule6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panel_matricule6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_matricule6Layout.createSequentialGroup()
                                .addComponent(txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(jLabel35)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel23)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel24)
                                .addGap(85, 85, 85)
                                .addComponent(jLabel25))
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panel_matricule6Layout.setVerticalGroup(
            panel_matricule6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panel_matricule6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule6Layout.createSequentialGroup()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_utilisateur.add(panel_matricule6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 270, 60));

        panel_matricule7.setBackground(new java.awt.Color(84, 127, 206));

        txt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel38.setText("nom :");

        javax.swing.GroupLayout panel_matricule7Layout = new javax.swing.GroupLayout(panel_matricule7);
        panel_matricule7.setLayout(panel_matricule7Layout);
        panel_matricule7Layout.setHorizontalGroup(
            panel_matricule7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel_matricule7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule7Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_matricule7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panel_matricule7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_matricule7Layout.createSequentialGroup()
                                .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(jLabel37)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel27)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel28)
                                .addGap(85, 85, 85)
                                .addComponent(jLabel29))
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panel_matricule7Layout.setVerticalGroup(
            panel_matricule7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(panel_matricule7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_matricule7Layout.createSequentialGroup()
                        .addGroup(panel_matricule7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_matricule7Layout.createSequentialGroup()
                        .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        panel_utilisateur.add(panel_matricule7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 270, 60));

        panel_matricule8.setBackground(new java.awt.Color(84, 127, 206));

        jLabel54.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel54.setText("adresse mail :");

        javax.swing.GroupLayout panel_matricule8Layout = new javax.swing.GroupLayout(panel_matricule8);
        panel_matricule8.setLayout(panel_matricule8Layout);
        panel_matricule8Layout.setHorizontalGroup(
            panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule8Layout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_matricule8Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_matricule8Layout.createSequentialGroup()
                                .addComponent(txt_adresse_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(jLabel53)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel33)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel34)
                                .addGap(85, 85, 85)
                                .addComponent(jLabel51))
                            .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panel_matricule8Layout.setVerticalGroup(
            panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule8Layout.createSequentialGroup()
                .addComponent(jLabel54)
                .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_matricule8Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panel_matricule8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_matricule8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_adresse_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        panel_utilisateur.add(panel_matricule8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 270, 60));

        panel_matricule5.setBackground(new java.awt.Color(84, 127, 206));

        jLabel50.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel50.setText("role :");

        combo_role.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        combo_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "commerciale", "planification", "methode", "stock" }));

        javax.swing.GroupLayout panel_matricule5Layout = new javax.swing.GroupLayout(panel_matricule5);
        panel_matricule5.setLayout(panel_matricule5Layout);
        panel_matricule5Layout.setHorizontalGroup(
            panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule5Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addGap(0, 0, 0)
                        .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(combo_role, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule5Layout.createSequentialGroup()
                        .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel49))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel45)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel46)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel47)))
                .addContainerGap())
        );
        panel_matricule5Layout.setVerticalGroup(
            panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_matricule5Layout.createSequentialGroup()
                        .addGroup(panel_matricule5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_matricule5Layout.createSequentialGroup()
                        .addComponent(combo_role)
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        panel_utilisateur.add(panel_matricule5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 270, 70));

        btn_ajouter.setBackground(new java.awt.Color(255, 255, 255));
        btn_ajouter.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_ajouter.setForeground(new java.awt.Color(51, 102, 255));
        btn_ajouter.setText("ajouter");
        btn_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouterActionPerformed(evt);
            }
        });
        panel_utilisateur.add(btn_ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 80, 30));

        btn_modifier.setBackground(new java.awt.Color(255, 255, 255));
        btn_modifier.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_modifier.setForeground(new java.awt.Color(51, 102, 255));
        btn_modifier.setText("modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });
        panel_utilisateur.add(btn_modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 90, 30));

        btn_supprimer.setBackground(new java.awt.Color(255, 255, 255));
        btn_supprimer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_supprimer.setForeground(new java.awt.Color(51, 102, 255));
        btn_supprimer.setText("supprimer");
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });
        panel_utilisateur.add(btn_supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 100, 30));

        panel_matricule9.setBackground(new java.awt.Color(84, 127, 206));

        jLabel60.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel60.setText("matricule :");

        javax.swing.GroupLayout panel_matricule9Layout = new javax.swing.GroupLayout(panel_matricule9);
        panel_matricule9.setLayout(panel_matricule9Layout);
        panel_matricule9Layout.setHorizontalGroup(
            panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matricule9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matricule9Layout.createSequentialGroup()
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_matricule9Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_matricule9Layout.createSequentialGroup()
                                .addComponent(txt_matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(jLabel59)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel55)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel56)
                                .addGap(85, 85, 85)
                                .addComponent(jLabel57))
                            .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panel_matricule9Layout.setVerticalGroup(
            panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matricule9Layout.createSequentialGroup()
                .addComponent(jLabel60)
                .addGroup(panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_matricule9Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panel_matricule9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_matricule9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        panel_utilisateur.add(panel_matricule9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 270, 60));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        table_utilisateur.setBackground(new java.awt.Color(102, 153, 255));
        table_utilisateur.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        table_utilisateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nom", "prenom", "adresse mail", "matricule", "mot de passe", "role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_utilisateur.setGridColor(new java.awt.Color(255, 255, 255));
        table_utilisateur.setRowHeight(22);
        table_utilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_utilisateurMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_utilisateur);
        if (table_utilisateur.getColumnModel().getColumnCount() > 0) {
            table_utilisateur.getColumnModel().getColumn(0).setResizable(false);
            table_utilisateur.getColumnModel().getColumn(1).setResizable(false);
            table_utilisateur.getColumnModel().getColumn(2).setResizable(false);
            table_utilisateur.getColumnModel().getColumn(3).setResizable(false);
            table_utilisateur.getColumnModel().getColumn(4).setResizable(false);
            table_utilisateur.getColumnModel().getColumn(5).setResizable(false);
        }

        log_out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.PNG"))); // NOI18N
        log_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log_outMouseClicked(evt);
            }
        });
        log_out.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                log_outKeyPressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("gestion des utilisateurs");

        txt_recherche.setBackground(new java.awt.Color(123, 156, 225));
        txt_recherche.setForeground(new java.awt.Color(255, 255, 255));
        txt_recherche.setBorder(null);
        txt_recherche.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_recherche.setPreferredSize(new java.awt.Dimension(2, 20));
        txt_recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rechercheActionPerformed(evt);
            }
        });
        txt_recherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rechercheKeyTyped(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/search-icon.png"))); // NOI18N
        jLabel2.setText("search");

        txt_nom_admin.setBackground(new java.awt.Color(0, 102, 255));
        txt_nom_admin.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txt_nom_admin.setForeground(new java.awt.Color(51, 102, 255));

        label_bulle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/bulle_icon.png"))); // NOI18N

        javax.swing.GroupLayout panel_gestion_utilisateurLayout = new javax.swing.GroupLayout(panel_gestion_utilisateur);
        panel_gestion_utilisateur.setLayout(panel_gestion_utilisateurLayout);
        panel_gestion_utilisateurLayout.setHorizontalGroup(
            panel_gestion_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_gestion_utilisateurLayout.createSequentialGroup()
                .addComponent(panel_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_gestion_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_gestion_utilisateurLayout.createSequentialGroup()
                        .addGroup(panel_gestion_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_gestion_utilisateurLayout.createSequentialGroup()
                                .addGap(307, 307, 307)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(744, 744, 744))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_gestion_utilisateurLayout.createSequentialGroup()
                                .addGroup(panel_gestion_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_gestion_utilisateurLayout.createSequentialGroup()
                                        .addGap(189, 189, 189)
                                        .addComponent(log_out)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panel_gestion_utilisateurLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panel_gestion_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(panel_gestion_utilisateurLayout.createSequentialGroup()
                                                .addComponent(txt_nom_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(label_bulle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(698, 698, 698)))
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_gestion_utilisateurLayout.createSequentialGroup()
                        .addGroup(panel_gestion_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_gestion_utilisateurLayout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_gestion_utilisateurLayout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addComponent(txt_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2)))
                        .addContainerGap())))
        );
        panel_gestion_utilisateurLayout.setVerticalGroup(
            panel_gestion_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_gestion_utilisateurLayout.createSequentialGroup()
                .addGroup(panel_gestion_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_gestion_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_utilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addGroup(panel_gestion_utilisateurLayout.createSequentialGroup()
                        .addGroup(panel_gestion_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nom_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_bulle))
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)
                        .addGap(59, 59, 59)
                        .addGroup(panel_gestion_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(log_out)
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_gestion_utilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_gestion_utilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        // supp
        
        
        
            String url;  
            Connection con = null;  
            try {  
                Class.forName("com.mysql.jdbc.Driver");  
            url="jdbc:mysql://localhost:3306/ahmed";  
                con = DriverManager.getConnection(url,"root","Aminedridi11");  
              //  System.out.println("mrigl");  
              
                }  
                catch (Exception e) {  
                System.out.println(e.toString());  
            }
            
        try {
            // login action
            
            Statement stm = con.createStatement();
            
            //execute query
            
            // input pour l'update celon la matricule
        
            
            String nom = txt_nom.getText();
            
            String prenom = txt_prenom.getText();
            
            String adresse_mail = txt_adresse_mail.getText();
            
            String matricule = txt_matricule.getText() ;
            
            String mot_de_passe = txt_mdp.getText();
            
            String role = combo_role.getSelectedItem().toString();
            
            //UPDATE client SET rue = '49 Rue Ameline',ville = 'Saint-Eustache-la-Forêt',code_postal = '76210' WHERE id = 2
        
              
         String sql =" DELETE FROM utilisateur WHERE matricule ='"+matricule+"'" ;       
         System.out.println(sql);
         
        
         
        PreparedStatement ps = con.prepareStatement(sql);
         
          ps.executeUpdate();
  
         
         System.out.println("le utilisateur de nom "+nom+" est supprimé !!!  ");
         
         JOptionPane.showMessageDialog(this,"le utilisateur de nom "+ nom +" est supprimé !!! ");
       
       
     
   
        } catch (SQLException ex) {
            
            System.out.println(ex.getMessage());
            
        }
        
        // supprimer la ligne selectionnée dans jtbale
        
         int SelectedRowIndex = table_utilisateur.getSelectedRow();
            
            
                
                 DefaultTableModel model2 = (DefaultTableModel) table_utilisateur.getModel();
                 // effacer la ligne selectionnée
                 
                 
                 model2.removeRow(SelectedRowIndex);
                 
                 
                 txt_nom.setText("");  txt_prenom.setText(""); txt_adresse_mail.setText(""); txt_matricule.setText(""); txt_mdp.setText(""); 
    
        
    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        // btn log out
        
        System.out.println("log out");

           this.dispose();
        
      login lg = new login();
      
      lg.setVisible(true);
        
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void log_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_outMouseClicked
        // btn log out

      // videer panel des utilisateurs 
      
      this.setTitle("login");
      
      
      this.panel_gestion_utilisateur.removeAll();
      
      this.panel_gestion_utilisateur.revalidate();
      
      this.panel_gestion_utilisateur.repaint();
      
      //  effacer le contenu du panel gestion users
      
      login lg = new login();
      
      
      // il faut panel login = panel user
      
      lg.getPanel_login().setPreferredSize( this.panel_gestion_utilisateur.getPreferredSize() );
      
      
      lg.getPanel_login().setLocation( this.panel_gestion_utilisateur.getLocation() );
      
      this.panel_gestion_utilisateur.add( lg.getPanel_login() );
      
      
    
    
    }//GEN-LAST:event_log_outMouseClicked

    private void log_outKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_log_outKeyPressed
        //log out
        
      
        
    }//GEN-LAST:event_log_outKeyPressed

    private void table_utilisateurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_utilisateurMouseClicked
       
        
         // table mouse clicked
        
        
        DefaultTableModel model3 = (DefaultTableModel) table_utilisateur.getModel();
        
        int SelectedRowIndex = table_utilisateur.getSelectedRow();
        
        
        
        txt_nom.setText(model3.getValueAt(SelectedRowIndex, 0).toString());
        
        txt_prenom.setText(model3.getValueAt(SelectedRowIndex, 1).toString());
        
        
        txt_adresse_mail.setText(model3.getValueAt(SelectedRowIndex, 2).toString());
        
        txt_matricule.setText(model3.getValueAt(SelectedRowIndex, 3).toString());
        
        txt_mdp.setText(model3.getValueAt(SelectedRowIndex, 4).toString());
        
        // txt_role.setText(model3.getValueAt(SelectedRowIndex, 5).toString());
         
     //    txt_role.getEditor().setItem(model3.getValueAt(SelectedRowIndex, 5).toString());
   
        combo_role.setSelectedItem(model3.getValueAt(SelectedRowIndex, 5).toString());
        
                                                   
        
    }//GEN-LAST:event_table_utilisateurMouseClicked

    private void txt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomActionPerformed

    private void btn_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouterActionPerformed
        // btn ajouter
        
        
        
        
       String url;  
            Connection con = null;  
            try {  
                Class.forName("com.mysql.jdbc.Driver");  
            url="jdbc:mysql://localhost:3306/ahmed";  
                con = DriverManager.getConnection(url,"root","Aminedridi11");  
              //  System.out.println("mrigl");  
              
                }  
                catch (Exception e) {  
                System.out.println(e.toString());  
            }
            
        try {
            // login action
            
            Statement stm = con.createStatement();
            
            //execute query
            String nom = txt_nom.getText();
            
            String prenom = txt_prenom.getText();
            
            String adresse_mail = txt_adresse_mail.getText();
            
            String matricule = txt_matricule.getText() ;
            
            String mot_de_passe = txt_mdp.getText();
            
            String role = combo_role.getSelectedItem().toString();
            
            
            
            
         
         
         String sql =" INSERT INTO utilisateur (nom,prenom,adresse_mail,matricule,mot_de_passe,role) VALUES ('"+nom+"','"+prenom+"','"+adresse_mail+"','"+matricule+"','"+mot_de_passe+"','"+role+"') " ;       
     
         System.out.println(sql);
      
         
        PreparedStatement ps = con.prepareStatement(sql);
         
          ps.executeUpdate();
  
         
         
         JOptionPane.showMessageDialog(this,"l'utilisateur de nom : " + nom +"est ajouté avec succés ");
         
       
       
     
   
       // remplir le tab avec nouveau utilisateur
       
    
                
                 DefaultTableModel model3 = (DefaultTableModel) table_utilisateur.getModel();
       
                 
                 
       Object[] table = new Object[6];
   
               
      table[0] = nom;
       
       table[1] = prenom;

       
       table[2] = adresse_mail;   
       
       
       table[3] = matricule;
       
        table[4] = mot_de_passe;
        
         table[5] = role;
       
                 
       
       model3.addRow(table);
       
      
      
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
        
        
        
    
        
    }//GEN-LAST:event_btn_ajouterActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
       
        
        // modifier utiliateur 
        
        // nom et prenom ne change pas dans la modification
        
        // modifier user
        
            String url;  
            Connection con = null;  
            try {  
                Class.forName("com.mysql.jdbc.Driver");  
            url="jdbc:mysql://localhost:3306/ahmed";  
                con = DriverManager.getConnection(url,"root","Aminedridi11");  
              //  System.out.println("mrigl");  
              
                }  
                catch (Exception e) {  
                System.out.println(e.toString());  
            }
            
        try {
            // login action
            
            Statement stm = con.createStatement();
            
            //execute query
            
            // input pour l'update celon la matricule
            
            String nom = txt_nom.getText();
            
            
            
            
            String prenom = txt_prenom.getText();
            
            String adresse_mail = txt_adresse_mail.getText();
            
            String matricule = txt_matricule.getText() ;
            
            String mot_de_passe = txt_mdp.getText();
            
            String role = combo_role.getSelectedItem().toString();
            
            //UPDATE client SET rue = '49 Rue Ameline',ville = 'Saint-Eustache-la-Forêt',code_postal = '76210' WHERE id = 2
        
              
         String sql =" UPDATE utilisateur SET nom = '"+nom+"',prenom ='"+prenom+"',matricule = '"+matricule+"',mot_de_passe= '"+mot_de_passe+"',role= '"+role+"' WHERE nom ='"+nom+"' AND prenom ='" + prenom +"'";       
         System.out.println(sql);
 
         
        PreparedStatement ps = con.prepareStatement(sql);
         
          ps.executeUpdate();
  
         
         
         
         JOptionPane.showMessageDialog(this,"le utilisateur de nom " + nom +" est modifié avec succés ");
       
       
     
   
       // ouvrir la page de consulation des utilisateurs 
      
        } catch (SQLException ex) {
          
            System.out.println(ex.getMessage());
            
        }
        // modifier le jtable
        
            int SelectedRowIndex = table_utilisateur.getSelectedRow();
            
            
                
                 DefaultTableModel model2 = (DefaultTableModel) table_utilisateur.getModel();
                 // effacer la ligne selectionnée
                 
                 
                 model2.removeRow(SelectedRowIndex);
                 
                 // ajouté la nouvelle ligne
                 
         
       Object[] table = new Object[6];
   
               
      table[0] = txt_nom.getText();
       
       table[1] = txt_prenom.getText();

       
       table[2] = txt_adresse_mail.getText();   
       
       
       table[3] = txt_matricule.getText();
       
        table[4] = txt_mdp.getText();
        
         table[5] = combo_role.getSelectedItem().toString();
       
       
       
       model2.addRow(table);
     
                 
            
        
    }//GEN-LAST:event_btn_modifierActionPerformed

    private void txt_rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rechercheActionPerformed

    private void txt_rechercheKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rechercheKeyTyped
        // txt recherche key typed
        
        
          //  System.out.println(" you typed " + txt_recherche.getText());
        
           
            
            txt_recherche.getDocument().addDocumentListener(new DocumentListener(){
            
                @Override
                public void insertUpdate(DocumentEvent de) {
                   System.out.println(" insert  " + txt_recherche.getText());
                   recherche(txt_recherche.getText());
                }

                @Override
                public void removeUpdate(DocumentEvent de) {
                    System.out.println(" update  " + txt_recherche.getText());
                    recherche(txt_recherche.getText());
                }

                @Override
                public void changedUpdate(DocumentEvent de) {
                  System.out.println(" delete  " + txt_recherche.getText());
                  recherche(txt_recherche.getText());
                }
            
                });
            
    }//GEN-LAST:event_txt_rechercheKeyTyped

    
    public void recherche(String text){
    
        
        String url;
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/ahmed";
            con = DriverManager.getConnection(url,"root","Aminedridi11");
            //  System.out.println("mrigl");

        }
        catch (Exception e) {
            System.out.println(e.toString());
        }

        try {
            // login action

            Statement stm = con.createStatement();

      
            
            
               // effacer le tab
                
                
                DefaultTableModel dm = (DefaultTableModel) table_utilisateur.getModel();
            int rowCount = dm.getRowCount();
            //Remove rows one by one from the end of the table
            for (int i = rowCount - 1; i >= 0; i--) {
         dm.removeRow(i);
            }
                
            
            
            
            
         
            // check user
            
            ResultSet rs ; 
            
            String sql1 = " SELECT * FROM `utilisateur` WHERE nom like '%"+text+"%' or prenom like '%"+ text +"%' or adresse_mail LIKE '%"+text+"%' or matricule like '%"+text+"%' or mot_de_passe like '%"+text+"%' or role like '%"+text+"%' ; ";

            System.out.println(sql1);
            
            rs =  stm.executeQuery(sql1);
            
            

            while(rs.next()){
                
             
            
                // remplir le tableau  avec la req select

                
                 String nom = rs.getString("nom");
                String prenom = rs.getString("prenom");
                   String adresse_mail = rs.getString("adresse_mail");
           String matricule = rs.getString("matricule");
                String mot_de_passe = rs.getString("mot_de_passe");
                  String role = rs.getString("role");
             

                
                System.out.println(" info === " +  nom  + prenom +   adresse_mail + matricule + mot_de_passe + role);
  

                // remplir le tableau 
                
               
       
       Object[] table = new Object[6];
   
               
      table[0] = nom;
       
       table[1] = prenom;

       
       table[2] = adresse_mail;   
       
       
       table[3] = matricule;
       
        table[4] = mot_de_passe;
        
         table[5] = role;
       
       
       
       dm.addRow(table);
       

            
           
            }
               
    }                                        

        catch(Exception ex){
            System.out.println(ex.getMessage());
        } 
        
        
    
    }
    
    
    
        // fonction pour remplir le tableau des utilisateurs
        
        
        private void remplir_users_tab(){
        
        
        ResultSet rs;
        String url;
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/ahmed";
            con = DriverManager.getConnection(url,"root","Aminedridi11");
            //  System.out.println("mrigl");

        }
        catch (Exception e) {
            System.out.println(e.toString());
        }

        try {
            // login action

            Statement stm = con.createStatement();

      

            rs =  stm.executeQuery("SELECT * FROM `utilisateur`");

            //rs = stm.executeQuery("SELECT * FROM admin");

            while(rs.next()){

                String nom = rs.getString("nom");
                String prenom = rs.getString("prenom");
                   String adresse_mail = rs.getString("adresse_mail");
           String matricule = rs.getString("matricule");
                String mot_de_passe = rs.getString("mot_de_passe");
                  String role = rs.getString("role");
             

                
             //   System.out.println(nom  + prenom +  + departement + mot_de_passe);
  

                // remplir le tableau 
                
                
                
                 DefaultTableModel model2 = (DefaultTableModel) table_utilisateur.getModel();
       
       Object[] table = new Object[6];
   
               
      table[0] = nom;
       
       table[1] = prenom;

       
       table[2] = adresse_mail;   
       
       
       table[3] = matricule;
       
        table[4] = mot_de_passe;
        
         table[5] = role;
       
       
       
       model2.addRow(table);
       

            }
        
        }
        
          catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
 
    }  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_utilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajouter;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_supprimer;
    private java.awt.Button button1;
    private javax.swing.JComboBox<String> combo_role;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel label_bulle;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel log_out;
    private javax.swing.JPanel panel_gestion_utilisateur;
    private javax.swing.JPanel panel_matricule4;
    private javax.swing.JPanel panel_matricule5;
    private javax.swing.JPanel panel_matricule6;
    private javax.swing.JPanel panel_matricule7;
    private javax.swing.JPanel panel_matricule8;
    private javax.swing.JPanel panel_matricule9;
    private javax.swing.JPanel panel_utilisateur;
    private javax.swing.JTable table_utilisateur;
    private javax.swing.JTextField txt_adresse_mail;
    private javax.swing.JTextField txt_matricule;
    private javax.swing.JPasswordField txt_mdp;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JLabel txt_nom_admin;
    private javax.swing.JTextField txt_prenom;
    private javax.swing.JTextField txt_recherche;
    // End of variables declaration//GEN-END:variables
}
