
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import swing.Home;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dridi family
 */
public class login extends javax.swing.JFrame {
    
    
    
        JPanel panel_user;
        
        JPanel panel_sign_up;

    public JPanel getPanel_user() {
        return panel_user;
    }

    public JPanel getPanel_cnp() {
        return panel_cnp;
    }

    public void setPanel_cnp(JPanel panel_cnp) {
        this.panel_cnp = panel_cnp;
    }

    public JPanel getPanel_login() {
        return panel_login;
    }

    public void setPanel_login(JPanel panel_login) {
        this.panel_login = panel_login;
    }

    public JPanel getPanel_sign_up() {
        return panel_sign_up;
    }


    public login() {
        initComponents();
     
        this.setTitle(" Login ");
       // this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        panel_cnp = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panel_login = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panel_matricule = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_matricule = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btn_login = new javax.swing.JLabel();
        btn_register = new javax.swing.JLabel();
        panel_mdp = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txt_mdp = new javax.swing.JPasswordField();
        radio_admin = new javax.swing.JRadioButton();
        radio_utilisateur = new javax.swing.JRadioButton();

        jPanel7.setBackground(new java.awt.Color(242, 247, 247));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Launch dates for the items listed ");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12/1/2018", "Expresso POS", "Kenya", null},
                {"12/1/2018", "ROM Gen", "US", null},
                {"12/1/2018", "Text Ed", "UK", null},
                {"12/1/2018", "Mola Con", "China", null}
            },
            new String [] {
                "Date", "Item", "Location", "Completed"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(22);
        jScrollPane1.setViewportView(jTable1);

        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel18)
                .addGap(54, 54, 54)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(41, 41, 41))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));

        panel_cnp.setBackground(new java.awt.Color(71, 120, 197));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_arabic.PNG"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_cnp1.JPG"))); // NOI18N

        javax.swing.GroupLayout panel_cnpLayout = new javax.swing.GroupLayout(panel_cnp);
        panel_cnp.setLayout(panel_cnpLayout);
        panel_cnpLayout.setHorizontalGroup(
            panel_cnpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cnpLayout.createSequentialGroup()
                .addGroup(panel_cnpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cnpLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_cnpLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel26)))
                .addGap(28, 28, 28))
        );
        panel_cnpLayout.setVerticalGroup(
            panel_cnpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cnpLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );

        panel_login.setBackground(new java.awt.Color(255, 255, 255));
        panel_login.setMaximumSize(new java.awt.Dimension(500, 500));
        panel_login.setMaximumSize(new java.awt.Dimension(500, 500));
        panel_login.setMinimumSize(new java.awt.Dimension(500, 500));
        panel_login.setPreferredSize(new java.awt.Dimension(500, 500));

        panel_matricule.setBackground(new java.awt.Color(84, 127, 206));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Matricule :");

        javax.swing.GroupLayout panel_matriculeLayout = new javax.swing.GroupLayout(panel_matricule);
        panel_matricule.setLayout(panel_matriculeLayout);
        panel_matriculeLayout.setHorizontalGroup(
            panel_matriculeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matriculeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel_matriculeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matriculeLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1))
                    .addGroup(panel_matriculeLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panel_matriculeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(txt_matricule)
                            .addGroup(panel_matriculeLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                                .addComponent(jLabel4)))))
                .addGap(40, 40, 40))
        );
        panel_matriculeLayout.setVerticalGroup(
            panel_matriculeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matriculeLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_matriculeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panel_matriculeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_matriculeLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_matriculeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.PNG"))); // NOI18N
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
        });
        btn_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_loginKeyPressed(evt);
            }
        });

        btn_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register.png"))); // NOI18N
        btn_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registerMouseClicked(evt);
            }
        });
        btn_register.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_registerKeyPressed(evt);
            }
        });

        panel_mdp.setBackground(new java.awt.Color(84, 127, 206));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setText("Mot de passe :");

        javax.swing.GroupLayout panel_mdpLayout = new javax.swing.GroupLayout(panel_mdp);
        panel_mdp.setLayout(panel_mdpLayout);
        panel_mdpLayout.setHorizontalGroup(
            panel_mdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mdpLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel_mdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_mdpLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_mdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(txt_mdp)))
                    .addGroup(panel_mdpLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panel_mdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_mdpLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(151, 151, 151))
                            .addGroup(panel_mdpLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel13)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22)))))
                .addGap(40, 40, 40))
        );
        panel_mdpLayout.setVerticalGroup(
            panel_mdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mdpLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_mdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panel_mdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_mdpLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_mdpLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(txt_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        radio_admin.setBackground(new java.awt.Color(51, 102, 255));
        radio_admin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        radio_admin.setForeground(new java.awt.Color(51, 102, 255));
        radio_admin.setText("admin");
        radio_admin.setContentAreaFilled(false);
        radio_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        radio_admin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radio_adminStateChanged(evt);
            }
        });
        radio_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_adminActionPerformed(evt);
            }
        });

        radio_utilisateur.setBackground(new java.awt.Color(51, 102, 255));
        radio_utilisateur.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        radio_utilisateur.setForeground(new java.awt.Color(51, 102, 255));
        radio_utilisateur.setText("utilisateur");
        radio_utilisateur.setContentAreaFilled(false);
        radio_utilisateur.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radio_utilisateurStateChanged(evt);
            }
        });
        radio_utilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_utilisateurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(btn_login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_register)
                        .addGap(130, 130, 130))
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_loginLayout.createSequentialGroup()
                                .addComponent(radio_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)
                                .addComponent(radio_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(panel_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panel_matricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(215, 215, 215))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel17))
                .addGap(41, 41, 41)
                .addComponent(panel_matricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(panel_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_utilisateur)
                    .addComponent(radio_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_login))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panel_cnp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_login, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_login, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addComponent(panel_cnp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        //LOGIN MOUSE CLICK

        System.out.println("login");
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // log out mouse click

        System.out.println("log out");
    }//GEN-LAST:event_jLabel19MouseClicked

    private void radio_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_adminActionPerformed

    private void radio_utilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_utilisateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_utilisateurActionPerformed

    private void btn_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_loginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loginKeyPressed

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        //login mouse click
        
        
        
        String url;
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            url="jdbc:mysql://localhost:3306/ahmed";
            con = DriverManager.getConnection(url,"root","Aminedridi11");
            //  System.out.println("mrigl");

        }
        catch (Exception e) {
            System.out.println(e.toString());
        }

     
            // login action

            try{
            
            Statement stm = null;
           
                
                
                
                stm = con.createStatement();
               
            //execute query
            String mot_de_passe = txt_mdp.getText();
            String matricule = txt_matricule.getText();
            
            
            // validation des champs
            
            if ( matricule.equals("") || mot_de_passe.equals("") ){
               
            JOptionPane.showMessageDialog(this, " remplir tous les champs !! ");
            }
            
         
            // check user
            
            else{
            
                
                if ( radio_utilisateur.isSelected() == true ){
            
                    try {
                        
                            
                      
            ResultSet rs ; 
            
            String sql1 = "SELECT * FROM `utilisateur` WHERE matricule='"+matricule +"' and mot_de_passe='"+mot_de_passe+"'";

            System.out.println(sql1);
            
                        
                        
                        rs =  stm.executeQuery(sql1);
                        
                        
                 
                    
                 //rs = stm.executeQuery("SELECT * FROM admin");

            if(rs.next()){
                

                if ( rs.getString("role").equals("commerciale") ) {
                
                   // fenetre d'acces aux comerciale
                   
      
                   JOptionPane.showMessageDialog(this, " user name = " + rs.getString("nom")+" a le role " + rs.getString("role") );
                   
                    this.setVisible(false);
                    Home hm = new Home(rs.getString("nom") , rs.getString("prenom") );
                    hm.setVisible(true);
                    
                }
                
                if ( rs.getString("role").equals("methode") ) {
                
                   // acces au methodes
                   
                   JOptionPane.showMessageDialog(this, " user name = " + rs.getString("nom")+" a le role " + rs.getString("role") );
                
                    this.setVisible(false);
                    Home hm = new Home(rs.getString("nom") , rs.getString("prenom") );
                    hm.setVisible(true);
                }
                
                if ( rs.getString("role").equals("stock") ) {
                
                   // acces aux stocks
                   
                   JOptionPane.showMessageDialog(this, " user name = " + rs.getString("nom")+" a le role " + rs.getString("role") );
                 
                   this.setVisible(false);
                    Home hm = new Home(rs.getString("nom") , rs.getString("prenom") );
                    hm.setVisible(true);
                    
                }
                
                if ( rs.getString("role").equals("planification") ) {
                
                   // acces aux plannification
                   
                   JOptionPane.showMessageDialog(this, " user name = " + rs.getString("nom")+" a le role " + rs.getString("role") );
                   
                    this.setVisible(false);
                    Home hm = new Home( rs.getString("nom") , rs.getString("prenom") );
                    hm.setVisible(true);
                }
                

            
            else{
            
              //  JOptionPane.showMessageDialog(this, " infos incorrecte !!!!! ");
              
              System.out.println("infos incorrecte !!!!! ");
            
            }
            
           
            }
            
            else{
            
                JOptionPane.showMessageDialog(this, "matricule ou mot de passe est incorrecte !");
            
            }
                
              
    }
                    
                
            
                        
                     catch (SQLException ex) {
                       System.out.println("utilisateur ex = " + ex.getMessage());
                    }
                    
              
                    
              
            
            

                    
                    
                
                }
                
                
                else{
                    
                    // radio admin
                    
                    
                     try {
                        
                            
                      
            ResultSet rs ; 
            
            String sql1 = "SELECT * FROM `admin` WHERE matricule='"+matricule +"' and mot_de_passe='"+mot_de_passe+"'";

            System.out.println(sql1);
            
                        
                        
                        rs =  stm.executeQuery(sql1);
                        
                        
                 
                    
                 //rs = stm.executeQuery("SELECT * FROM admin");

            if(rs.next()){
     
                try {
                    JOptionPane.showMessageDialog(this, " admin name = " + rs.getString("nom") );
                
                    
                     
        
        // panel utilisateur
        
        
        this.setTitle("login");
        
        System.out.println("login");
        
       
          
      panel_login.removeAll();
      
      panel_login.revalidate();
      
      panel_login.repaint();
       
   
      Gestion_utilisateur a =  new Gestion_utilisateur(rs.getString("nom") , rs.getString("prenom") );
      
      
        panel_login.setPreferredSize( new Dimension(a.getPanel_gestion_utilisateur().getHeight()+170 , a.getPanel_gestion_utilisateur().getWidth()+170 ) );
        
        
      
        
        panel_login.add( a.getPanel_gestion_utilisateur() ) ;
                    
                    
      
                    }
                
            
                        
                     catch (SQLException ex) {
                       System.out.println("admin ex :" + ex.getMessage());
                    }
                    
              
                    
              
                    
                }
                    
                    
                    
                }
      
        
        catch(Exception ex){
            
         System.out.println(ex.getMessage());   
            
        }
        
        
        
        
                }   
                
            }
    }       catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
       

       
        
    }//GEN-LAST:event_btn_loginMouseClicked

    private void btn_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registerMouseClicked
       
        
        this.setTitle("register");
        // location + size
           
        
        // vider panel login
        
        
        this.setTitle(" register ");
      this.panel_login.removeAll();
      
      this.panel_login.revalidate();
      
      this.panel_login.repaint();
        
      
      
      register rg = new register();
      
     // rg.getPanel_register().setPreferredSize( this.panel_login.getPreferredSize() );
      
    //  rg.getPanel_register().setLocation( this.panel_login.getLocation() );
      
      
      this.panel_login.add( rg.getPanel_register() );
      
    }//GEN-LAST:event_btn_registerMouseClicked

    private void btn_registerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_registerKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registerKeyPressed

    private void radio_utilisateurStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radio_utilisateurStateChanged
        // radio utilisateur change state
       
        if ( radio_utilisateur.isSelected() == true ){
        
            System.out.println(" radio utilisateur is selected");
        
        radio_admin.setSelected(false);
            
        }
        
        else {
        
            System.out.println(" radio utilisateur is not selected ");
            
        
        }
        
     
        
    }//GEN-LAST:event_radio_utilisateurStateChanged

    private void radio_adminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radio_adminStateChanged
        // radio admin
        
        if ( radio_admin.isSelected() == true ){
        
            System.out.println(" radio admin is selected ");
        
            
            radio_utilisateur.setSelected(false);
            
        }
        
        else{
        
        System.out.println(" radio admin is not selected ");
        }
        
        
    }//GEN-LAST:event_radio_adminStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_login;
    private javax.swing.JLabel btn_register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panel_cnp;
    public javax.swing.JPanel panel_login;
    private javax.swing.JPanel panel_matricule;
    private javax.swing.JPanel panel_mdp;
    private javax.swing.JRadioButton radio_admin;
    private javax.swing.JRadioButton radio_utilisateur;
    private javax.swing.JTextField txt_matricule;
    private javax.swing.JPasswordField txt_mdp;
    // End of variables declaration//GEN-END:variables
}
